//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Stream;

/// <summary>
/// Request parameters for 
/// Operation: GET /OEmbed
/// </summary>
public partial class OEmbedGetOEmbedRequest : BaseRequest
{
  /// <summary>
  /// url
  /// </summary>
  [JsonPropertyName("url")]
  public string? Url { get; set; }

  /// <summary>
  /// maxWidth
  /// </summary>
  [JsonPropertyName("maxWidth")]
  public int? MaxWidth { get; set; }

  /// <summary>
  /// maxHeight
  /// </summary>
  [JsonPropertyName("maxHeight")]
  public int? MaxHeight { get; set; }

  /// <summary>
  /// token
  /// </summary>
  [JsonPropertyName("token")]
  public string? Token { get; set; }

  /// <summary>
  /// expires
  /// </summary>
  [JsonPropertyName("expires")]
  public long? Expires { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Url != null)
      queryParams["url"] = Url;
    if (MaxWidth != null)
      queryParams["maxWidth"] = MaxWidth;
    if (MaxHeight != null)
      queryParams["maxHeight"] = MaxHeight;
    if (Token != null)
      queryParams["token"] = Token;
    if (Expires != null)
      queryParams["expires"] = Expires;

    return queryParams.ToQueryString();
  }
}
