//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Stream;

/// <summary>
/// Request parameters for Fetch Video
/// Operation: POST /library/{libraryId}/videos/fetch
/// </summary>
public partial class VideoFetchNewVideoRequest : BaseRequest
{
  /// <summary>
  /// collectionId
  /// </summary>
  [JsonPropertyName("collectionId")]
  public string? CollectionId { get; set; }

  /// <summary>
  /// (Optional) Video time in ms to extract the main video thumbnail.
  /// </summary>
  [JsonPropertyName("thumbnailTime")]
  public int? ThumbnailTime { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (CollectionId != null)
      queryParams["collectionId"] = CollectionId;
    if (ThumbnailTime != null)
      queryParams["thumbnailTime"] = ThumbnailTime;

    return queryParams.ToQueryString();
  }
}
