//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Stream;

/// <summary>
/// Request parameters for Cleanup unconfigured resolutions
/// Operation: POST /library/{libraryId}/videos/{videoId}/resolutions/cleanup
/// </summary>
public partial class VideoDeleteResolutionsRequest : BaseRequest
{
  /// <summary>
  /// resolutionsToDelete
  /// </summary>
  [JsonPropertyName("resolutionsToDelete")]
  public string? ResolutionsToDelete { get; set; }

  /// <summary>
  /// deleteNonConfiguredResolutions
  /// </summary>
  [JsonPropertyName("deleteNonConfiguredResolutions")]
  public bool? DeleteNonConfiguredResolutions { get; set; }

  /// <summary>
  /// allResolutions
  /// </summary>
  [JsonPropertyName("allResolutions")]
  public bool? AllResolutions { get; set; }

  /// <summary>
  /// deleteOriginal
  /// </summary>
  [JsonPropertyName("deleteOriginal")]
  public bool? DeleteOriginal { get; set; }

  /// <summary>
  /// Outputs to clean. Supported values: hls, mp4, all
  /// </summary>
  [JsonPropertyName("outputs")]
  public string? Outputs { get; set; }

  /// <summary>
  /// deleteMp4Files
  /// </summary>
  [JsonPropertyName("deleteMp4Files")]
  public bool? DeleteMp4Files { get; set; }

  /// <summary>
  /// If set to true, no actual file manipulation will happen, only informational data will be returned
  /// </summary>
  [JsonPropertyName("dryRun")]
  public bool? DryRun { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (ResolutionsToDelete != null)
      queryParams["resolutionsToDelete"] = ResolutionsToDelete;
    if (DeleteNonConfiguredResolutions != null)
      queryParams["deleteNonConfiguredResolutions"] = DeleteNonConfiguredResolutions;
    if (AllResolutions != null)
      queryParams["allResolutions"] = AllResolutions;
    if (DeleteOriginal != null)
      queryParams["deleteOriginal"] = DeleteOriginal;
    if (Outputs != null)
      queryParams["outputs"] = Outputs;
    if (DeleteMp4Files != null)
      queryParams["deleteMp4Files"] = DeleteMp4Files;
    if (DryRun != null)
      queryParams["dryRun"] = DryRun;

    return queryParams.ToQueryString();
  }
}
