//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Stream;

/// <summary>
/// Request parameters for Repackage Video
/// Operation: POST /library/{libraryId}/videos/{videoId}/repackage
/// </summary>
public partial class VideoRepackageRequest : BaseRequest
{
  /// <summary>
  /// Marks whether previous file versions should be kept in storage, allows for faster repackage later on. Default is true.
  /// </summary>
  [JsonPropertyName("keepOriginalFiles")]
  public bool? KeepOriginalFiles { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (KeepOriginalFiles != null)
      queryParams["keepOriginalFiles"] = KeepOriginalFiles;

    return queryParams.ToQueryString();
  }
}
