//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Request parameters for List API Keys
/// Operation: GET /apikey
/// </summary>
public partial class ApiKeyPublicGetApiKeysByAccountEndpointRequest : BaseRequest
{
  /// <summary>
  /// page
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// perPage
  /// </summary>
  [JsonPropertyName("perPage")]
  public int? PerPage { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Page != null)
      queryParams["page"] = Page;
    if (PerPage != null)
      queryParams["perPage"] = PerPage;

    return queryParams.ToQueryString();
  }
}
