//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Request parameters for Get DNS Zone
/// Operation: GET /dnszone/{id}
/// </summary>
public partial class DnsZonePublicIndex2Request : BaseRequest
{
  /// <summary>
  /// view
  /// </summary>
  [JsonPropertyName("view")]
  public string? View { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (View != null)
      queryParams["view"] = View;

    return queryParams.ToQueryString();
  }
}
