//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Request parameters for 
/// Operation: GET /user/audit/{date}
/// </summary>
public partial class GetUserAuditLogEndpointGetUserAuditLogRequest : BaseRequest
{
  /// <summary>
  /// Product
  /// </summary>
  [JsonPropertyName("Product")]
  public List<string>? Product { get; set; }

  /// <summary>
  /// ResourceType
  /// </summary>
  [JsonPropertyName("ResourceType")]
  public List<string>? ResourceType { get; set; }

  /// <summary>
  /// ResourceId
  /// </summary>
  [JsonPropertyName("ResourceId")]
  public List<string>? ResourceId { get; set; }

  /// <summary>
  /// ActorId
  /// </summary>
  [JsonPropertyName("ActorId")]
  public List<string>? ActorId { get; set; }

  /// <summary>
  /// Order
  /// </summary>
  [JsonPropertyName("Order")]
  public string? Order { get; set; }

  /// <summary>
  /// ContinuationToken
  /// </summary>
  [JsonPropertyName("ContinuationToken")]
  public string? ContinuationToken { get; set; }

  /// <summary>
  /// Limit
  /// </summary>
  [JsonPropertyName("Limit")]
  public int? Limit { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Product != null)
      queryParams["Product"] = Product;
    if (ResourceType != null)
      queryParams["ResourceType"] = ResourceType;
    if (ResourceId != null)
      queryParams["ResourceId"] = ResourceId;
    if (ActorId != null)
      queryParams["ActorId"] = ActorId;
    if (Order != null)
      queryParams["Order"] = Order;
    if (ContinuationToken != null)
      queryParams["ContinuationToken"] = ContinuationToken;
    if (Limit != null)
      queryParams["Limit"] = Limit;

    return queryParams.ToQueryString();
  }
}
