//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Request parameters for Get Statistics
/// Operation: GET /statistics
/// </summary>
public partial class StatisticsPublicGetStatisticsRequest : BaseRequest
{
  /// <summary>
  /// (Optional) The start date of the statistics. If no value is passed, the last 30 days will be returned.
  /// </summary>
  [JsonPropertyName("dateFrom")]
  public DateTimeOffset? DateFrom { get; set; }

  /// <summary>
  /// (Optional) The end date of the statistics. If no value is passed, the last 30 days will be returned.
  /// </summary>
  [JsonPropertyName("dateTo")]
  public DateTimeOffset? DateTo { get; set; }

  /// <summary>
  /// (Optional) If set, the statistics will be only returned for the given Pull Zone
  /// </summary>
  [JsonPropertyName("pullZone")]
  public long? PullZone { get; set; }

  /// <summary>
  /// (Optional) If set, the statistics will be only returned for the given region ID
  /// </summary>
  [JsonPropertyName("serverZoneId")]
  public long? ServerZoneId { get; set; }

  /// <summary>
  /// (Optional) If set, the respose will contain the non-2xx response
  /// </summary>
  [JsonPropertyName("loadErrors")]
  public bool? LoadErrors { get; set; }

  /// <summary>
  /// (Optional) If true, the statistics data will be returned in hourly groupping.
  /// </summary>
  [JsonPropertyName("hourly")]
  public bool? Hourly { get; set; }

  /// <summary>
  /// (Optional) If true and hourly=true, the exact hour components of dateFrom and dateTo will be preserved instead of rounding to full-day boundaries.
  /// </summary>
  [JsonPropertyName("exactRange")]
  public bool? ExactRange { get; set; }

  /// <summary>
  /// Load Origin Response Times
  /// </summary>
  [JsonPropertyName("loadOriginResponseTimes")]
  public bool? LoadOriginResponseTimes { get; set; }

  /// <summary>
  /// Load Origin Traffic
  /// </summary>
  [JsonPropertyName("loadOriginTraffic")]
  public bool? LoadOriginTraffic { get; set; }

  /// <summary>
  /// Load Requests Served
  /// </summary>
  [JsonPropertyName("loadRequestsServed")]
  public bool? LoadRequestsServed { get; set; }

  /// <summary>
  /// Load Bandwidth Used
  /// </summary>
  [JsonPropertyName("loadBandwidthUsed")]
  public bool? LoadBandwidthUsed { get; set; }

  /// <summary>
  /// Load Origin Shield Bandwidth
  /// </summary>
  [JsonPropertyName("loadOriginShieldBandwidth")]
  public bool? LoadOriginShieldBandwidth { get; set; }

  /// <summary>
  /// Load Geographic Traffic Distribution
  /// </summary>
  [JsonPropertyName("loadGeographicTrafficDistribution")]
  public bool? LoadGeographicTrafficDistribution { get; set; }

  /// <summary>
  /// Load User Balance History
  /// </summary>
  [JsonPropertyName("loadUserBalanceHistory")]
  public bool? LoadUserBalanceHistory { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (DateFrom != null)
      queryParams["dateFrom"] = DateFrom;
    if (DateTo != null)
      queryParams["dateTo"] = DateTo;
    if (PullZone != null)
      queryParams["pullZone"] = PullZone;
    if (ServerZoneId != null)
      queryParams["serverZoneId"] = ServerZoneId;
    if (LoadErrors != null)
      queryParams["loadErrors"] = LoadErrors;
    if (Hourly != null)
      queryParams["hourly"] = Hourly;
    if (ExactRange != null)
      queryParams["exactRange"] = ExactRange;
    if (LoadOriginResponseTimes != null)
      queryParams["loadOriginResponseTimes"] = LoadOriginResponseTimes;
    if (LoadOriginTraffic != null)
      queryParams["loadOriginTraffic"] = LoadOriginTraffic;
    if (LoadRequestsServed != null)
      queryParams["loadRequestsServed"] = LoadRequestsServed;
    if (LoadBandwidthUsed != null)
      queryParams["loadBandwidthUsed"] = LoadBandwidthUsed;
    if (LoadOriginShieldBandwidth != null)
      queryParams["loadOriginShieldBandwidth"] = LoadOriginShieldBandwidth;
    if (LoadGeographicTrafficDistribution != null)
      queryParams["loadGeographicTrafficDistribution"] = LoadGeographicTrafficDistribution;
    if (LoadUserBalanceHistory != null)
      queryParams["loadUserBalanceHistory"] = LoadUserBalanceHistory;

    return queryParams.ToQueryString();
  }
}
