//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Request parameters for Reset Read-Only Password
/// Operation: POST /storagezone/resetReadOnlyPassword
/// </summary>
public partial class StorageZonePublicResetReadOnlyPasswordRequest : BaseRequest
{
  /// <summary>
  /// The ID of the storage zone that should have the read-only password reset
  /// </summary>
  [JsonPropertyName("id")]
  public long? Id { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Id != null)
      queryParams["id"] = Id;

    return queryParams.ToQueryString();
  }
}
