//
// <auto-generated>
// Bunny Storage API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/storage.json
// API: bunny.net Edge Storage API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Storage;

/// <summary>
/// Request parameters for Delete File
/// Operation: DELETE /{storageZoneName}/{path}/{fileName}
/// </summary>
public partial class DeleteManageFilesRequest : BaseRequest
{
  /// <summary>
  /// Set to `true` to bypass the root directory deletion guard and delete the storage zone root (`/`).
  /// </summary>
  [JsonPropertyName("allowRootDelete")]
  public string? AllowRootDelete { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (AllowRootDelete != null)
      queryParams["allowRootDelete"] = AllowRootDelete;

    return queryParams.ToQueryString();
  }
}
