//
// <auto-generated>
// Bunny Storage API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/storage.json
// API: bunny.net Edge Storage API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Storage.Models;

/// <summary>
/// ErrorObject from OpenAPI schema.
/// Schema path: #/components/schemas/ErrorObject
/// </summary>
public partial class ErrorObject
{
  /// <summary>
  /// The error status code of the request
  /// </summary>
  public int? HttpCode { get; set; }

  /// <summary>
  /// The error description message
  /// </summary>
  public string? Message { get; set; }
}
