//
// <auto-generated>
// Bunny EdgeScripting API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/edge-scripting.json
// API: bunny.net Compute API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using Apigen.Bunny.EdgeScripting.Models;
using Microsoft.Extensions.Logging;

#nullable enable

namespace Apigen.Bunny.EdgeScripting;

/// <summary>
/// Main API client for accessing all resources
/// </summary>
public partial class BunnyEdgeScriptingClient : IDisposable
{
  private readonly HttpClient _httpClient;
  private readonly bool _disposeHttpClient;
  private readonly ILogger? _logger;

  /// <summary>
  /// Client for Code operations
  /// </summary>
  public CodeClient Code { get; }

  /// <summary>
  /// Client for Edge Script operations
  /// </summary>
  public EdgeScriptClient EdgeScript { get; }

  /// <summary>
  /// Client for Variable operations
  /// </summary>
  public VariableClient Variable { get; }

  /// <summary>
  /// Client for Secret operations
  /// </summary>
  public SecretClient Secret { get; }

  /// <summary>
  /// Client for Release operations
  /// </summary>
  public ReleaseClient Release { get; }

  /// <summary>
  /// Initialize client with a pre-configured HttpClient
  /// </summary>
  /// <param name="httpClient">Pre-configured HttpClient with base address, auth headers, etc.</param>
  /// <param name="logger">Optional logger for request/response logging</param>
  public BunnyEdgeScriptingClient(HttpClient httpClient, ILogger? logger = null)
  {
    _httpClient = httpClient;
    _disposeHttpClient = false;
    _logger = logger;

    Code = new CodeClient(_httpClient, _logger);
    EdgeScript = new EdgeScriptClient(_httpClient, _logger);
    Variable = new VariableClient(_httpClient, _logger);
    Secret = new SecretClient(_httpClient, _logger);
    Release = new ReleaseClient(_httpClient, _logger);
  }

  private BunnyEdgeScriptingClient(HttpClient httpClient, bool disposeHttpClient, ILogger? logger)
  {
    _httpClient = httpClient;
    _disposeHttpClient = disposeHttpClient;
    _logger = logger;

    Code = new CodeClient(_httpClient, _logger);
    EdgeScript = new EdgeScriptClient(_httpClient, _logger);
    Variable = new VariableClient(_httpClient, _logger);
    Secret = new SecretClient(_httpClient, _logger);
    Release = new ReleaseClient(_httpClient, _logger);
  }

  /// <summary>
  /// Create client with API key authentication
  /// </summary>
  public static BunnyEdgeScriptingClient WithAccessKey(string accessKey, string baseUrl = "https://api.bunny.net", ILogger? logger = null)
  {
    HttpClient httpClient = CreateTokenAuthHttpClient(accessKey, baseUrl, "AccessKey", false);
    return new BunnyEdgeScriptingClient(httpClient, true, logger);
  }

  /// <summary>
  /// Create client with API key authentication
  /// </summary>
  public static BunnyEdgeScriptingClient WithBearer(string bearer, string baseUrl = "https://api.bunny.net", ILogger? logger = null)
  {
    HttpClient httpClient = CreateTokenAuthHttpClient(bearer, baseUrl, "Authorization", false);
    return new BunnyEdgeScriptingClient(httpClient, true, logger);
  }

  private static HttpClient CreateTokenAuthHttpClient(string apiToken, string baseUrl, string headerName, bool useBearer)
  {
    // Ensure baseUrl ends with / for proper Uri combining with relative paths
    string normalizedBaseUrl = baseUrl.EndsWith("/") ? baseUrl : baseUrl + "/";
    HttpClient client = new() { BaseAddress = new Uri(normalizedBaseUrl) };

    if (useBearer)
    {
      client.DefaultRequestHeaders.Add(headerName, $"Bearer {apiToken}");
    }
    else
    {
      client.DefaultRequestHeaders.Add(headerName, apiToken);
    }

    return client;
  }

  private static HttpClient CreateBasicAuthHttpClient(string username, string password, string baseUrl)
  {
    // Ensure baseUrl ends with / for proper Uri combining with relative paths
    string normalizedBaseUrl = baseUrl.EndsWith("/") ? baseUrl : baseUrl + "/";
    HttpClient client = new() { BaseAddress = new Uri(normalizedBaseUrl) };

    string credentials = Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"{username}:{password}"));
    client.DefaultRequestHeaders.Add("Authorization", $"Basic {credentials}");

    return client;
  }

  private static HttpClient CreateCookieAuthHttpClient(string token, string cookieName, string baseUrl)
  {
    string normalizedBaseUrl = baseUrl.EndsWith("/") ? baseUrl : baseUrl + "/";
    System.Net.CookieContainer cookies = new();
    cookies.Add(new Uri(normalizedBaseUrl), new System.Net.Cookie(cookieName, token));
    HttpClientHandler handler = new() { CookieContainer = cookies };
    HttpClient client = new(handler) { BaseAddress = new Uri(normalizedBaseUrl) };

    return client;
  }

  /// <summary>
  /// Dispose resources
  /// </summary>
  public void Dispose()
  {
    if (_disposeHttpClient)
    {
      _httpClient?.Dispose();
    }
  }
}
