//
// <auto-generated>
// Bunny EdgeScripting API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/edge-scripting.json
// API: bunny.net Compute API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.EdgeScripting.Models;

#nullable enable

namespace Apigen.Bunny.EdgeScripting;

/// <summary>
/// Interface for Secret operations
/// </summary>
public partial interface ISecretClient
{
  /// <summary>
  /// Add Secret
  /// Operation: POST /compute/script/{id}/secrets
  /// </summary>
  Task<EdgeScriptSecretModel> AddEdgeScriptSecretEndpointAddEdgeScriptAsync(long id, Apigen.Bunny.EdgeScripting.Models.EdgeScriptAddSecretModel edgeScriptAddSecretModel, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Secrets
  /// Operation: GET /compute/script/{id}/secrets
  /// </summary>
  Task<ListEdgeScriptSecretsModel> ListEdgeScriptSecretsEndpointListEdgeScriptAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Upsert Secret
  /// Operation: PUT /compute/script/{id}/secrets
  /// </summary>
  Task<EdgeScriptSecretModel> UpsertEdgeScriptSecretEndpointUpsertEdgeScriptAsync(long id, Apigen.Bunny.EdgeScripting.Models.EdgeScriptUpsertSecretModel edgeScriptUpsertSecretModel, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Secret
  /// Operation: DELETE /compute/script/{id}/secrets/{secretId}
  /// </summary>
  Task DeleteEdgeScriptSecretEndpointDeleteAsync(long id, long secretId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Secret
  /// Operation: POST /compute/script/{id}/secrets/{secretId}
  /// </summary>
  Task<EdgeScriptSecretModel> UpdateEdgeScriptSecretEndpointUpdateEdgeScriptAsync(long id, long secretId, Apigen.Bunny.EdgeScripting.Models.EdgeScriptUpdateSecretModel edgeScriptUpdateSecretModel, CancellationToken cancellationToken = default);

}
