//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// ApiGuardianEndpointMetrics from OpenAPI schema.
/// Schema path: #/components/schemas/ApiGuardianEndpointMetrics
/// </summary>
public partial class ApiGuardianEndpointMetrics
{
  [System.Text.Json.Serialization.JsonPropertyName("totalBlockedRequests")]
  public long? TotalBlockedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalLoggedRequests")]
  public long? TotalLoggedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalRateLimited")]
  public long? TotalRateLimited { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalRequestsInspected")]
  public long? TotalRequestsInspected { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalFailedRequestValidation")]
  public long? TotalFailedRequestValidation { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalFailedAuthenticationEnforcement")]
  public long? TotalFailedAuthenticationEnforcement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overviewPastTwentyEightDays")]
  public Dictionary<string, ApiGuardianEndpointActivity>? OverviewPastTwentyEightDays { get; set; }
}
