//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// ApiGuardianConfigurationDetails from OpenAPI schema.
/// Schema path: #/components/schemas/ApiGuardianConfigurationDetails
/// 
/// Global API Guardian configuration for a shield zone.
/// </summary>
public partial class ApiGuardianConfigurationDetails
{
  [System.Text.Json.Serialization.JsonPropertyName("shieldZoneId")]
  public int? ShieldZoneId { get; set; }

  /// <summary>
  /// Whether API Guardian is enabled for this shield zone. When disabled, no requests are inspected.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
  public bool? IsEnabled { get; set; }

  /// <summary>
  /// 0 = Log
  /// 1 = Block
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("executionMode")]
  public WafExecutionMode? ExecutionMode { get; set; }

  /// <summary>
  /// 0 = Block
  /// 1 = Log
  /// 2 = Ignore
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bodyLimitAction")]
  public WafPayloadLimitAction? BodyLimitAction { get; set; }

  /// <summary>
  /// 0 = Block
  /// 1 = Log
  /// 2 = Ignore
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("unmatchedPathAction")]
  public UnmatchedPathAction? UnmatchedPathAction { get; set; }

  /// <summary>
  /// The info.title field from the uploaded OpenAPI specification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The info.version field from the uploaded OpenAPI specification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }

  /// <summary>
  /// Plan limit: maximum number of endpoints that can be defined in the specification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxEndpoints")]
  public int? MaxEndpoints { get; set; }

  /// <summary>
  /// Plan limit: maximum number of properties a single schema object may declare.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxFieldsPerType")]
  public int? MaxFieldsPerType { get; set; }

  /// <summary>
  /// Plan limit: maximum depth of nested $ref, items, and properties chains.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxNestingDepth")]
  public int? MaxNestingDepth { get; set; }

  /// <summary>
  /// Plan limit: combined node count across all components/schemas entries.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxTotalSchemaNodes")]
  public int? MaxTotalSchemaNodes { get; set; }

  /// <summary>
  /// Plan limit: combined character length of all pattern regex strings in the specification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("maxTotalRegexLength")]
  public int? MaxTotalRegexLength { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
  public DateTimeOffset? CreatedAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
  public DateTimeOffset? UpdatedAt { get; set; }
}
