//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// 0 = None
/// 1 = Block
/// 2 = Allow
/// 3 = Ignore
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<BotCategorizationAction>))]
public enum BotCategorizationAction
{
    None = 0,
    Block = 1,
    Allow = 2,
    Ignore = 3,
}
