//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// BotCategorizationGroup from OpenAPI schema.
/// Schema path: #/components/schemas/BotCategorizationGroup
/// </summary>
public partial class BotCategorizationGroup
{
  /// <summary>
  /// 0 = None
  /// 1 = SEO
  /// 2 = AIScraper
  /// 3 = AITool
  /// 4 = Tool
  /// 5 = Ads
  /// 6 = Preview
  /// 7 = Social
  /// 255 = System
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("category")]
  public BotCategory Category { get; set; }

  /// <summary>
  /// 0 = None
  /// 1 = Block
  /// 2 = Allow
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("categoryAction")]
  public BotCategoryAction CategoryAction { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("bots")]
  public List<BotCategorizationDetails>? Bots { get; set; }
}
