//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// 0 = LogOnly
/// 1 = Challenge
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<BotDetectionExecutionMode>))]
public enum BotDetectionExecutionMode
{
    LogOnly = 0,
    Challenge = 1,
}
