//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// CreateCustomWafRuleModelVariableTypes from OpenAPI schema.
/// Schema path: #/components/schemas/CreateCustomWafRuleModelVariableTypes
/// </summary>
public partial class CreateCustomWafRuleModelVariableTypes
{
  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_URI")]
  public string? RequestUri { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_URI_RAW")]
  public string? RequestUriRaw { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS")]
  public string? Args { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS_COMBINED_SIZE")]
  public string? ArgsCombinedSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS_GET")]
  public string? ArgsGet { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS_GET_NAMES")]
  public string? ArgsGetNames { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS_POST")]
  public string? ArgsPost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ARGS_POST_NAMES")]
  public string? ArgsPostNames { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("FILES_NAMES")]
  public string? FilesNames { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("GEO")]
  public string? Geo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REMOTE_ADDR")]
  public string? RemoteAddr { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("QUERY_STRING")]
  public string? QueryString { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_BASENAME")]
  public string? RequestBasename { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_BODY")]
  public string? RequestBody { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_COOKIES_NAMES")]
  public string? RequestCookiesNames { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_COOKIES")]
  public string? RequestCookies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_FILENAME")]
  public string? RequestFilename { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_HEADERS_NAMES")]
  public string? RequestHeadersNames { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_HEADERS")]
  public string? RequestHeaders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_LINE")]
  public string? RequestLine { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_METHOD")]
  public string? RequestMethod { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("REQUEST_PROTOCOL")]
  public string? RequestProtocol { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("RESPONSE_BODY")]
  public string? ResponseBody { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("RESPONSE_HEADERS")]
  public string? ResponseHeaders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("RESPONSE_STATUS")]
  public string? ResponseStatus { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("FINGERPRINT")]
  public string? Fingerprint { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("VERIFIED_BOT_CATEGORY")]
  public string? VerifiedBotCategory { get; set; }
}
