//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// CreateCustomWafRuleModel from OpenAPI schema.
/// Schema path: #/components/schemas/CreateCustomWafRuleModel
/// </summary>
public partial class CreateCustomWafRuleModel
{
  /// <summary>
  /// 1 = Block
  /// 2 = Log
  /// 3 = Challenge
  /// 4 = Allow
  /// 5 = Bypass
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("actionType")]
  public WafRuleActionType? ActionType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("variableTypes")]
  public CreateCustomWafRuleModelVariableTypes? VariableTypes { get; set; }

  /// <summary>
  /// 0 = BEGINSWITH
  /// 1 = ENDSWITH
  /// 2 = CONTAINS
  /// 3 = CONTAINSWORD
  /// 4 = STRMATCH
  /// 5 = EQ
  /// 6 = GE
  /// 7 = GT
  /// 8 = LE
  /// 9 = LT
  /// 12 = WITHIN
  /// 14 = RX
  /// 15 = STREQ
  /// 17 = DETECTSQLI
  /// 18 = DETECTXSS
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("operatorType")]
  public WafRuleOperatorType? OperatorType { get; set; }

  /// <summary>
  /// 0 = NOTICE
  /// 1 = WARNING
  /// 2 = CRITICAL
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("severityType")]
  public WafRuleSeverityType? SeverityType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("transformationTypes")]
  public List<WafRuleTransformationType>? TransformationTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isNegated")]
  public bool? IsNegated { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isRegexVariable")]
  public bool? IsRegexVariable { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("chainedRuleConditions")]
  public List<WafChainedRuleConditionItem>? ChainedRuleConditions { get; set; }
}
