//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// EventLogsFilter from OpenAPI schema.
/// Schema path: #/components/schemas/EventLogsFilter
/// 
/// A single Event Logs filter clause.
/// </summary>
public partial class EventLogsFilter
{
  /// <summary>
  /// Dimension to filter on: feature, ruleId, ip, ja4, ua, url, asn, country or action.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("field")]
  public string? Field { get; set; }

  /// <summary>
  /// Operator: eq, in, contains, cidr (ip only, IPv4/IPv6) or wildcard (&apos;*&apos; matches any run).
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("op")]
  public string? Op { get; set; }

  /// <summary>
  /// Value(s) for the filter; multiple values are OR-combined.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public List<string?>? Value { get; set; }
}
