//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// EventRow from OpenAPI schema.
/// Schema path: #/components/schemas/EventRow
/// 
/// A single event returned in a flat (ungrouped) search.
/// </summary>
public partial class EventRow
{
  /// <summary>
  /// Unique event identifier.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("logId")]
  public string? LogId { get; set; }

  /// <summary>
  /// Event time as Unix time in milliseconds (UTC).
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
  public long? Timestamp { get; set; }

  /// <summary>
  /// The full request context for the event (JSON object).
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("log")]
  public object? Log { get; set; }

  /// <summary>
  /// Resolved dimension values for the event (e.g. ip, ruleId, url, ja4).
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fields")]
  public Dictionary<string, string?>? Fields { get; set; }
}
