//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// GenericRequestResponse from OpenAPI schema.
/// Schema path: #/components/schemas/GenericRequestResponse
/// 
/// Generic response object containing status information for API operations.
/// </summary>
public partial class GenericRequestResponse
{
  /// <summary>
  /// 100 = Continue
  /// 101 = SwitchingProtocols
  /// 102 = Processing
  /// 103 = EarlyHints
  /// 200 = OK
  /// 201 = Created
  /// 202 = Accepted
  /// 203 = NonAuthoritativeInformation
  /// 204 = NoContent
  /// 205 = ResetContent
  /// 206 = PartialContent
  /// 207 = MultiStatus
  /// 208 = AlreadyReported
  /// 226 = IMUsed
  /// 300 = MultipleChoices
  /// 300 = Ambiguous
  /// 301 = MovedPermanently
  /// 301 = Moved
  /// 302 = Found
  /// 302 = Redirect
  /// 303 = SeeOther
  /// 303 = RedirectMethod
  /// 304 = NotModified
  /// 305 = UseProxy
  /// 306 = Unused
  /// 307 = TemporaryRedirect
  /// 307 = RedirectKeepVerb
  /// 308 = PermanentRedirect
  /// 400 = BadRequest
  /// 401 = Unauthorized
  /// 402 = PaymentRequired
  /// 403 = Forbidden
  /// 404 = NotFound
  /// 405 = MethodNotAllowed
  /// 406 = NotAcceptable
  /// 407 = ProxyAuthenticationRequired
  /// 408 = RequestTimeout
  /// 409 = Conflict
  /// 410 = Gone
  /// 411 = LengthRequired
  /// 412 = PreconditionFailed
  /// 413 = RequestEntityTooLarge
  /// 414 = RequestUriTooLong
  /// 415 = UnsupportedMediaType
  /// 416 = RequestedRangeNotSatisfiable
  /// 417 = ExpectationFailed
  /// 421 = MisdirectedRequest
  /// 422 = UnprocessableEntity
  /// 422 = UnprocessableContent
  /// 423 = Locked
  /// 424 = FailedDependency
  /// 426 = UpgradeRequired
  /// 428 = PreconditionRequired
  /// 429 = TooManyRequests
  /// 431 = RequestHeaderFieldsTooLarge
  /// 451 = UnavailableForLegalReasons
  /// 500 = InternalServerError
  /// 501 = NotImplemented
  /// 502 = BadGateway
  /// 503 = ServiceUnavailable
  /// 504 = GatewayTimeout
  /// 505 = HttpVersionNotSupported
  /// 506 = VariantAlsoNegotiates
  /// 507 = InsufficientStorage
  /// 508 = LoopDetected
  /// 510 = NotExtended
  /// 511 = NetworkAuthenticationRequired
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("statusCode")]
  public HttpStatusCode? StatusCode { get; set; }

  /// <summary>
  /// Indicates whether the operation was successful.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("success")]
  public bool? Success { get; set; }

  /// <summary>
  /// Human-readable message describing the result of the operation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  /// <summary>
  /// Unique error key for programmatic error handling, if applicable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("errorKey")]
  public string? ErrorKey { get; set; }
}
