//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// GetTriggeredRulesResponse from OpenAPI schema.
/// Schema path: #/components/schemas/GetTriggeredRulesResponse
/// </summary>
public partial class GetTriggeredRulesResponse
{
  /// <summary>
  /// Generic response object containing status information for API operations.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("errorResponse")]
  public GenericRequestResponse? ErrorResponse { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("triggeredRules")]
  public List<TriggeredRuleItem>? TriggeredRules { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalTriggeredRules")]
  public int? TotalTriggeredRules { get; set; }
}
