//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// Labels from OpenAPI schema.
/// Schema path: #/components/schemas/Labels
/// </summary>
public partial class Labels
{
  [System.Text.Json.Serialization.JsonPropertyName("asn")]
  public string? Asn { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("country")]
  public string? Country { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ruleId")]
  public string? RuleId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("severity")]
  public string? Severity { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("method")]
  public string? Method { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ruleGroup")]
  public string? RuleGroup { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("serverZone")]
  public string? ServerZone { get; set; }
}
