//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// OverageSegment from OpenAPI schema.
/// Schema path: #/components/schemas/OverageSegment
/// </summary>
public partial class OverageSegment
{
  [System.Text.Json.Serialization.JsonPropertyName("periodStart")]
  public DateTimeOffset? PeriodStart { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("periodEnd")]
  public DateTimeOffset? PeriodEnd { get; set; }

  /// <summary>
  /// 0 = Basic
  /// 1 = Advanced
  /// 2 = Business
  /// 3 = Enterprise
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("planType")]
  public ShieldPlanType? PlanType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overageAllowance")]
  public long? OverageAllowance { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overage")]
  public long? Overage { get; set; }
}
