//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// Ratelimit from OpenAPI schema.
/// Schema path: #/components/schemas/Ratelimit
/// </summary>
public partial class Ratelimit
{
  [System.Text.Json.Serialization.JsonPropertyName("totalBreaches")]
  public int? TotalBreaches { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("loggedBreaches")]
  public int? LoggedBreaches { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("challengedBreaches")]
  public int? ChallengedBreaches { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("blockedBreaches")]
  public int? BlockedBreaches { get; set; }
}
