//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// RequestIntegrityConfiguration from OpenAPI schema.
/// Schema path: #/components/schemas/RequestIntegrityConfiguration
/// </summary>
public partial class RequestIntegrityConfiguration
{
  /// <summary>
  /// 0 = Off
  /// 1 = Low
  /// 2 = Medium
  /// 3 = High
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sensitivity")]
  public BotDetectionSensitivity? Sensitivity { get; set; }
}
