//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// ShieldZoneUploadScanningMetrics from OpenAPI schema.
/// Schema path: #/components/schemas/ShieldZoneUploadScanningMetrics
/// </summary>
public partial class ShieldZoneUploadScanningMetrics
{
  [System.Text.Json.Serialization.JsonPropertyName("overviewPastTwentyEightDays")]
  public Dictionary<string, UploadScanning>? OverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalLoggedRequests")]
  public int? TotalLoggedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalBlockedRequests")]
  public int? TotalBlockedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalFilesScanned")]
  public int? TotalFilesScanned { get; set; }
}
