//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// ShieldZoneResponse from OpenAPI schema.
/// Schema path: #/components/schemas/ShieldZoneResponse
/// </summary>
public partial class ShieldZoneResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("shieldZoneId")]
  public long? ShieldZoneId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("pullZoneId")]
  public long? PullZoneId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("learningMode")]
  public bool? LearningMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("learningModeUntil")]
  public DateTimeOffset? LearningModeUntil { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafEnabled")]
  public bool? WafEnabled { get; set; }

  /// <summary>
  /// 0 = Log
  /// 1 = Block
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("wafExecutionMode")]
  public WafExecutionMode? WafExecutionMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafDisabledRules")]
  public List<string?>? WafDisabledRules { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafLogOnlyRules")]
  public List<string?>? WafLogOnlyRules { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafCustomRuleOrder")]
  public List<long>? WafCustomRuleOrder { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafRequestHeaderLoggingEnabled")]
  public bool? WafRequestHeaderLoggingEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requestBodyLoggingEnabled")]
  public bool? RequestBodyLoggingEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafRequestIgnoredHeaders")]
  public List<string?>? WafRequestIgnoredHeaders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafRealtimeThreatIntelligenceEnabled")]
  public bool? WafRealtimeThreatIntelligenceEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafProfileId")]
  public int? WafProfileId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wafEngineConfig")]
  public List<PullZoneWafConfigVariableModel>? WafEngineConfig { get; set; }

  /// <summary>
  /// 0 = Block
  /// 1 = Log
  /// 2 = Ignore
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("wafRequestBodyLimitAction")]
  public WafPayloadLimitAction? WafRequestBodyLimitAction { get; set; }

  /// <summary>
  /// 0 = Block
  /// 1 = Log
  /// 2 = Ignore
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("wafResponseBodyLimitAction")]
  public WafPayloadLimitAction? WafResponseBodyLimitAction { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rateLimitRulesLimit")]
  public int? RateLimitRulesLimit { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("customWafRulesLimit")]
  public int? CustomWafRulesLimit { get; set; }

  /// <summary>
  /// 0 = Basic
  /// 1 = Advanced
  /// 2 = Business
  /// 3 = Enterprise
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("planType")]
  public ShieldPlanType? PlanType { get; set; }

  /// <summary>
  /// 0 = Off
  /// 1 = Low
  /// 2 = Medium
  /// 3 = High
  /// 4 = Challenge
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dDoSShieldSensitivity")]
  public DDoSShieldSensitivity? DDoSShieldSensitivity { get; set; }

  /// <summary>
  /// 0 = Log
  /// 1 = Block
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dDoSExecutionMode")]
  public DDoSExecutionMode? DDoSExecutionMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dDoSChallengeWindow")]
  public int? DDoSChallengeWindow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("whitelabelResponsePages")]
  public bool? WhitelabelResponsePages { get; set; }
}
