//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// ShieldZoneMetrics from OpenAPI schema.
/// Schema path: #/components/schemas/ShieldZoneMetrics
/// </summary>
public partial class ShieldZoneMetrics
{
  [System.Text.Json.Serialization.JsonPropertyName("overview")]
  public ShieldOverview? Overview { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("waf")]
  public Waf? Waf { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overviewPastTwentyEightDays")]
  public Dictionary<string, ShieldOverview>? OverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dDoS")]
  public DDoS? DDoS { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dDoSOverviewPastTwentyEightDays")]
  public Dictionary<string, DDoS>? DDoSOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ratelimit")]
  public Ratelimit? Ratelimit { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ratelimitOverviewPastTwentyEightDays")]
  public Dictionary<string, Ratelimit>? RatelimitOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("botDetection")]
  public BotDetectionData? BotDetection { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("botDetectionOverviewPastTwentyEightDays")]
  public Dictionary<string, BotDetectionData>? BotDetectionOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessList")]
  public AccessList? AccessList { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessListOverviewPastTwentyEightDays")]
  public Dictionary<string, AccessList>? AccessListOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("uploadScanningOverviewPastTwentyEightDays")]
  public Dictionary<string, UploadScanning>? UploadScanningOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("apiGuardian")]
  public ApiGuardianEndpointActivity? ApiGuardian { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("apiGuardianOverviewPastTwentyEightDays")]
  public Dictionary<string, ApiGuardianEndpointActivity>? ApiGuardianOverviewPastTwentyEightDays { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalCleanRequestsLimit")]
  public long? TotalCleanRequestsLimit { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalBillableRequests")]
  public long? TotalBillableRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("uploadScanning")]
  public UploadScanning? UploadScanning { get; set; }
}
