//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// UnauthorizedResult from OpenAPI schema.
/// Schema path: #/components/schemas/UnauthorizedResult
/// </summary>
public partial class UnauthorizedResult
{
  [System.Text.Json.Serialization.JsonPropertyName("statusCode")]
  public int? StatusCode { get; set; }
}
