//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// UpdateAccessListConfigurationRequest from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateAccessListConfigurationRequest
/// 
/// Request model for updating an access list configuration.
/// </summary>
public partial class UpdateAccessListConfigurationRequest
{
  /// <summary>
  /// Whether the access list should be enabled or disabled. If null, the current state is preserved.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
  public bool? IsEnabled { get; set; }

  /// <summary>
  /// 0 = None
  /// 1 = Allow
  /// 2 = Block
  /// 3 = Challenge
  /// 4 = Log
  /// 5 = Bypass
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public AccessListAction? Action { get; set; }
}
