//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// UpdateReviewTriggeredRuleResponse from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateReviewTriggeredRuleResponse
/// </summary>
public partial class UpdateReviewTriggeredRuleResponse
{
  /// <summary>
  /// Generic response object containing status information for API operations.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("errorResponse")]
  public GenericRequestResponse? ErrorResponse { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("success")]
  public bool? Success { get; set; }
}
