//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// UploadScanning from OpenAPI schema.
/// Schema path: #/components/schemas/UploadScanning
/// </summary>
public partial class UploadScanning
{
  [System.Text.Json.Serialization.JsonPropertyName("loggedRequests")]
  public int? LoggedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("blockedRequests")]
  public int? BlockedRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("filesScanned")]
  public int? FilesScanned { get; set; }
}
