//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// UpsertOpenApiSpecificationResponse from OpenAPI schema.
/// Schema path: #/components/schemas/UpsertOpenApiSpecificationResponse
/// 
/// Represents the response for uploading or updating an OpenAPI specification in API Guardian.
/// </summary>
public partial class UpsertOpenApiSpecificationResponse
{
  /// <summary>
  /// Generic response object containing status information for API operations.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public GenericRequestResponse? Error { get; set; }

  /// <summary>
  /// The full API Guardian state for a shield zone: global configuration and all endpoints.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public ApiGuardianConfigurationResponse? Data { get; set; }
}
