//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// WafProfileMinimal from OpenAPI schema.
/// Schema path: #/components/schemas/WafProfileMinimal
/// </summary>
public partial class WafProfileMinimal
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isPremium")]
  public bool? IsPremium { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("profileCategory")]
  public string? ProfileCategory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("imageUrl")]
  public string? ImageUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("features")]
  public string? Features { get; set; }
}
