//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// 30 = ForThirtySeconds
/// 60 = ForOneMinute
/// 300 = ForFiveMinutes
/// 900 = ForFifteenMinutes
/// 1800 = ForThirtyMinutes
/// 3600 = ForOneHour
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<WafRatelimitBlockType>))]
public enum WafRatelimitBlockType
{
    ForThirtySeconds = 30,
    ForOneMinute = 60,
    ForFiveMinutes = 300,
    ForFifteenMinutes = 900,
    ForThirtyMinutes = 1800,
    ForOneHour = 3600,
}
