//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// 0 = IP
/// 1 = Host
/// 2 = Country
/// 3 = City
/// 4 = ASN
/// 5 = Organization
/// 6 = JA4
/// 7 = IP_JA4
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<WafRatelimitCounterKeyType>))]
public enum WafRatelimitCounterKeyType
{
    IP = 0,
    Host = 1,
    Country = 2,
    City = 3,
    Asn = 4,
    Organization = 5,
    JA4 = 6,
    IPJA4 = 7,
}
