//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Shield.Models;

/// <summary>
/// WafRuleGroupModel from OpenAPI schema.
/// Schema path: #/components/schemas/WafRuleGroupModel
/// </summary>
public partial class WafRuleGroupModel
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public long? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("code")]
  public string? Code { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fileName")]
  public string? FileName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mainGroup")]
  public string? MainGroup { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ruleset")]
  public string? Ruleset { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rules")]
  public List<WafRuleModel>? Rules { get; set; }
}
