//
// <auto-generated>
// Bunny Logging API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/logging.json
// API: bunny.net CDN Logging
// Version: v2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Logging;

/// <summary>
/// Request parameters for Query CDN access logs for a pull zone.
/// Operation: GET /v2/pullzones/{pullZoneId}/logs
/// </summary>
public partial class GetLoggingV2Request : BaseRequest
{
  /// <summary>
  /// Inclusive start of the time range (UTC). Defaults to `To - 24h`.
  /// Must fall within the 3-day log retention window. The total range
  /// (`To - From`) cannot exceed 3 days.
  /// </summary>
  [JsonPropertyName("from")]
  public DateTimeOffset? From { get; set; }

  /// <summary>
  /// Exclusive end of the time range (UTC). Defaults to `now`.
  /// </summary>
  [JsonPropertyName("to")]
  public DateTimeOffset? To { get; set; }

  /// <summary>
  /// Comma-separated list of HTTP status filters. Each entry can be an exact
  /// code (e.g. `200`, `404`) or a status class (e.g. `2xx`, `5xx`).
  /// Multiple entries are combined with OR.
  /// </summary>
  [JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Comma-separated list of cache statuses to match exactly (e.g. `HIT,MISS,EXPIRED`).
  /// </summary>
  [JsonPropertyName("cacheStatus")]
  public string? CacheStatus { get; set; }

  /// <summary>
  /// ISO 3166 alpha-2 country code (e.g. `EE`). Multiple values can be comma-separated.
  /// </summary>
  [JsonPropertyName("country")]
  public string? Country { get; set; }

  /// <summary>
  /// Edge location / server zone (exact match).
  /// </summary>
  [JsonPropertyName("edgeLocation")]
  public string? EdgeLocation { get; set; }

  /// <summary>
  /// Client IP address filter (IPv4 or IPv6). The match width adapts to the zone&apos;s
  /// IP anonymization setting so the filter can never reveal information beyond
  /// what the API returns: exact match when anonymization is disabled, /24 (IPv4)
  /// or /64 (IPv6) when last-octet anonymization is enabled, and ignored when full
  /// anonymization is enabled.
  /// </summary>
  [JsonPropertyName("remoteIp")]
  public string? RemoteIp { get; set; }

  /// <summary>
  /// Case-insensitive substring match against the request URL (host + path).
  /// </summary>
  [JsonPropertyName("urlContains")]
  public string? UrlContains { get; set; }

  /// <summary>
  /// Case-insensitive substring match against the User-Agent header.
  /// </summary>
  [JsonPropertyName("userAgentContains")]
  public string? UserAgentContains { get; set; }

  /// <summary>
  /// Case-insensitive substring match against the Referer header.
  /// </summary>
  [JsonPropertyName("refererContains")]
  public string? RefererContains { get; set; }

  /// <summary>
  /// Free-text, case-insensitive token search. Tokens are space-separated; a row
  /// matches if ANY token appears in ANY of the searched columns: cache status,
  /// request ID, edge location, host, path, user agent, referer, and (for zones
  /// with extended logging) content range. Remote IP, country code, and the
  /// authorization header are not searched. use the dedicated filters for those,
  /// or note that the authorization header is encrypted at rest. Limited to 16
  /// tokens of at most 128 characters each.
  /// </summary>
  [JsonPropertyName("search")]
  public string? Search { get; set; }

  /// <summary>
  /// Exact request ID (UUID) to look up a single log entry.
  /// </summary>
  [JsonPropertyName("requestId")]
  public string? RequestId { get; set; }

  /// <summary>
  /// Include origin-shield (edge → shield) requests. Defaults to `false` to match v1.
  /// </summary>
  [JsonPropertyName("includeOriginShield")]
  public bool? IncludeOriginShield { get; set; }

  /// <summary>
  /// Maximum entries to return. Defaults to 100. Capped at 10000.
  /// </summary>
  [JsonPropertyName("limit")]
  public int? Limit { get; set; }

  /// <summary>
  /// Number of entries to skip. Defaults to 0.
  /// </summary>
  [JsonPropertyName("offset")]
  public long? Offset { get; set; }

  /// <summary>
  /// Sort order by timestamp: `asc` or `desc` (default).
  /// </summary>
  [JsonPropertyName("order")]
  public string? Order { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (From != null)
      queryParams["from"] = From;
    if (To != null)
      queryParams["to"] = To;
    if (Status != null)
      queryParams["status"] = Status;
    if (CacheStatus != null)
      queryParams["cacheStatus"] = CacheStatus;
    if (Country != null)
      queryParams["country"] = Country;
    if (EdgeLocation != null)
      queryParams["edgeLocation"] = EdgeLocation;
    if (RemoteIp != null)
      queryParams["remoteIp"] = RemoteIp;
    if (UrlContains != null)
      queryParams["urlContains"] = UrlContains;
    if (UserAgentContains != null)
      queryParams["userAgentContains"] = UserAgentContains;
    if (RefererContains != null)
      queryParams["refererContains"] = RefererContains;
    if (Search != null)
      queryParams["search"] = Search;
    if (RequestId != null)
      queryParams["requestId"] = RequestId;
    if (IncludeOriginShield != null)
      queryParams["includeOriginShield"] = IncludeOriginShield;
    if (Limit != null)
      queryParams["limit"] = Limit;
    if (Offset != null)
      queryParams["offset"] = Offset;
    if (Order != null)
      queryParams["order"] = Order;

    return queryParams.ToQueryString();
  }
}
