//
// <auto-generated>
// Bunny EdgeScripting API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/edge-scripting.json
// API: bunny.net Compute API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.EdgeScripting.Models;

/// <summary>
/// EdgeScriptReleaseModel from OpenAPI schema.
/// Schema path: #/components/schemas/EdgeScriptReleaseModel
/// </summary>
public partial class EdgeScriptReleaseModel
{
  public long? Id { get; set; }

  public bool? Deleted { get; set; }

  public string? Code { get; set; }

  public string? Uuid { get; set; }

  public string? Note { get; set; }

  public string? Author { get; set; }

  public string? AuthorEmail { get; set; }

  public string? CommitSha { get; set; }

  /// <summary>
  /// 0 = Archived
  /// 1 = Live
  /// </summary>
  public EdgeScriptReleaseStatus? Status { get; set; }

  public DateTimeOffset? DateReleased { get; set; }

  public DateTimeOffset? DatePublished { get; set; }
}
