//
// <auto-generated>
// Bunny EdgeScripting API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/edge-scripting.json
// API: bunny.net Compute API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.EdgeScripting.Models;

/// <summary>
/// 0 = Archived
/// 1 = Live
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<EdgeScriptReleaseStatus>))]
public enum EdgeScriptReleaseStatus
{
    Archived = 0,
    Live = 1,
}
