//
// <auto-generated>
// Bunny EdgeScripting API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/edge-scripting.json
// API: bunny.net Compute API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.EdgeScripting.Models;

/// <summary>
/// PaginationListModelOfEdgeScriptModel from OpenAPI schema.
/// Schema path: #/components/schemas/PaginationListModelOfEdgeScriptModel
/// </summary>
public partial class PaginationListModelOfEdgeScriptModel
{
  public List<EdgeScriptModel>? Items { get; set; }

  public int? CurrentPage { get; set; }

  public int? TotalItems { get; set; }

  public bool? HasMoreItems { get; set; }
}
