//
// <auto-generated>
// Bunny OriginErrors API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/origin-errors.json
// API: Origin Errors API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.OriginErrors.Models;
using Microsoft.Extensions.Logging;

#nullable enable

namespace Apigen.Bunny.OriginErrors;

/// <summary>
/// Client for OriginErrors operations
/// </summary>
public partial class OriginErrorsClient
{
  private readonly HttpClient _httpClient;
  private readonly ILogger? _logger;

  internal OriginErrorsClient(HttpClient httpClient, ILogger? logger = null)
  {
    _httpClient = httpClient;
    _logger = logger;
  }

  /// <summary>
  /// Get origin error logs for a specific Pull Zone and date
  /// Operation: GET /{pullZoneId}/{dateTime}
  /// </summary>
  public async Task<LogResponse> GetAsync(int pullZoneId, string dateTime, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["pullZoneId"] = pullZoneId,
      ["dateTime"] = dateTime
    };
    string url = "{pullZoneId}/{dateTime}".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "GET", url);
      HttpResponseMessage response = await _httpClient.GetAsync(url, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "GET", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "GET", url, errorBody, null);
        throw new ApiException(response.StatusCode, "GET", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      LogResponse? result = JsonSerializer.Deserialize<LogResponse>(responseContent, JsonConfig.Default);
      return result ?? new LogResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "GET", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "GET", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "GET", url, ex);
      throw;
    }
  }


}
