//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Base class for request objects
/// </summary>
public abstract partial class BaseRequest
{
  public virtual string ToQueryString() => string.Empty;
}
