//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Core.Models;

#nullable enable

namespace Apigen.Bunny.Core;

/// <summary>
/// Interface for Region operations
/// </summary>
public partial interface IRegionClient
{
  /// <summary>
  /// Region list
  /// Operation: GET /region
  /// </summary>
  Task<List<RegionModel>> ListAsync(CancellationToken cancellationToken = default);

}
