//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// AddBlockedReferrerRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/AddBlockedReferrerRequestModel
/// </summary>
public partial class AddBlockedReferrerRequestModel
{
  /// <summary>
  /// The hostname that will be added as a blocked referer
  /// </summary>
  [Required]
  [MinLength(1)]
  public string? Hostname { get; set; }
}
