//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// AddCertificateRequestModel from OpenAPI schema.
/// Schema path: #/components/schemas/AddCertificateRequestModel
/// </summary>
public partial class AddCertificateRequestModel
{
  /// <summary>
  /// The hostname to which the hostname will be added
  /// </summary>
  [Required]
  [MinLength(1)]
  public string? Hostname { get; set; }

  /// <summary>
  /// The Base64 encoded binary data of the certificate file
  /// </summary>
  [Required]
  [MinLength(1)]
  public string? Certificate { get; set; }

  /// <summary>
  /// The Base64 encoded binary data of the certificate key file
  /// </summary>
  [Required]
  [MinLength(1)]
  public string? CertificateKey { get; set; }
}
