//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// BillingRecordModel from OpenAPI schema.
/// Schema path: #/components/schemas/BillingRecordModel
/// </summary>
public partial class BillingRecordModel
{
  /// <summary>
  /// The ID of the billing record
  /// </summary>
  public long? Id { get; set; }

  /// <summary>
  /// The external ID of the payment
  /// </summary>
  public string? PaymentId { get; set; }

  /// <summary>
  /// The amount linked to the record model
  /// </summary>
  public double? Amount { get; set; }

  /// <summary>
  /// The payer reference that sent the payment
  /// </summary>
  public string? Payer { get; set; }

  /// <summary>
  /// The date and time when the billing record was created
  /// </summary>
  public DateTimeOffset? Timestamp { get; set; }

  /// <summary>
  /// The type of the billing record. PayPal = 0, Crypto = 1, CreditCard = 2, MonthlyUsage = 3, Refund = 4, CouponCode = 5, BankTransfer = 6, AffiliateCredits = 7
  /// </summary>
  public BillingRecordType? Type { get; set; }

  /// <summary>
  /// Determines if an invoice is available
  /// </summary>
  public bool? InvoiceAvailable { get; set; }

  /// <summary>
  /// The URL where the invoice or document can be downloaded. Null if this is not available.
  /// </summary>
  public string? DocumentDownloadUrl { get; set; }

  /// <summary>
  /// The URL where the document with product usage breakdown can be downloaded. Null if this is not available.
  /// </summary>
  public string? DetailedDocumentDownloadUrl { get; set; }
}
