//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// BillingSummaryItem from OpenAPI schema.
/// Schema path: #/components/schemas/BillingSummaryItem
/// </summary>
public partial class BillingSummaryItem
{
  /// <summary>
  /// The ID of the pull zone
  /// </summary>
  public long? PullZoneId { get; set; }

  /// <summary>
  /// The total credit amount used in this month by the Pull Zone
  /// </summary>
  public decimal? MonthlyUsage { get; set; }

  /// <summary>
  /// The total monthly bandwidth used by the pull zone
  /// </summary>
  public long? MonthlyBandwidthUsed { get; set; }
}
