//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = A
/// 1 = AAAA
/// 2 = CNAME
/// 3 = TXT
/// 4 = MX
/// 5 = Redirect
/// 6 = Flatten
/// 7 = PullZone
/// 8 = SRV
/// 9 = CAA
/// 10 = PTR
/// 11 = Script
/// 12 = NS
/// 13 = SVCB
/// 14 = HTTPS
/// 15 = TLSA
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<DnsRecordTypes>))]
public enum DnsRecordTypes
{
    A = 0,
    Aaaa = 1,
    Cname = 2,
    Txt = 3,
    MX = 4,
    Redirect = 5,
    Flatten = 6,
    PullZone = 7,
    Srv = 8,
    Caa = 9,
    Ptr = 10,
    Script = 11,
    NS = 12,
    Svcb = 13,
    Https = 14,
    Tlsa = 15,
}
