//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// DnsZoneDiscoveredRecordModel from OpenAPI schema.
/// Schema path: #/components/schemas/DnsZoneDiscoveredRecordModel
/// </summary>
public partial class DnsZoneDiscoveredRecordModel
{
  /// <summary>
  /// Record name relative to the zone. &apos;@&apos; represents apex.
  /// </summary>
  public string? Name { get; set; }

  public object? Type { get; set; }

  public int? Ttl { get; set; }

  public string? Value { get; set; }

  public int? Priority { get; set; }

  public int? Weight { get; set; }

  public int? Port { get; set; }

  public bool? IsProxied { get; set; }
}
