//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// DnsZoneAddModel from OpenAPI schema.
/// Schema path: #/components/schemas/DnsZoneAddModel
/// </summary>
public partial class DnsZoneAddModel
{
  /// <summary>
  /// The domain that will be added.
  /// </summary>
  [Required]
  [MinLength(1)]
  public string? Domain { get; set; }

  /// <summary>
  /// Optional array of DNS records to add when creating the zone.
  /// </summary>
  public List<AddDnsRecordModel>? Records { get; set; }
}
