//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = ForceSSL
/// 1 = Redirect
/// 2 = OriginUrl
/// 3 = OverrideCacheTime
/// 4 = BlockRequest
/// 5 = SetResponseHeader
/// 6 = SetRequestHeader
/// 7 = ForceDownload
/// 8 = DisableTokenAuthentication
/// 9 = EnableTokenAuthentication
/// 10 = OverrideCacheTimePublic
/// 11 = IgnoreQueryString
/// 12 = DisableOptimizer
/// 13 = ForceCompression
/// 14 = SetStatusCode
/// 15 = BypassPermaCache
/// 16 = OverrideBrowserCacheTime
/// 17 = OriginStorage
/// 18 = SetNetworkRateLimit
/// 19 = SetConnectionLimit
/// 20 = SetRequestsPerSecondLimit
/// 21 = RunEdgeScript
/// 22 = OriginMagicContainers
/// 23 = DisableWAF
/// 24 = RetryOrigin
/// 25 = OverrideBrowserCacheResponseHeader
/// 26 = RemoveBrowserCacheResponseHeader
/// 27 = DisableShieldChallenge
/// 28 = DisableShield
/// 29 = DisableShieldBotDetection
/// 30 = BypassAwsS3Authentication
/// 31 = DisableShieldAccessLists
/// 32 = DisableShieldRateLimiting
/// 33 = EnableRequestCoalescing
/// 34 = DisableRequestCoalescing
/// 37 = StripCookiesClientToOrigin
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<EdgeRuleActionType>))]
public enum EdgeRuleActionType
{
    ForceSsl = 0,
    Redirect = 1,
    OriginUrl = 2,
    OverrideCacheTime = 3,
    BlockRequest = 4,
    SetResponseHeader = 5,
    SetRequestHeader = 6,
    ForceDownload = 7,
    DisableTokenAuthentication = 8,
    EnableTokenAuthentication = 9,
    OverrideCacheTimePublic = 10,
    IgnoreQueryString = 11,
    DisableOptimizer = 12,
    ForceCompression = 13,
    SetStatusCode = 14,
    BypassPermaCache = 15,
    OverrideBrowserCacheTime = 16,
    OriginStorage = 17,
    SetNetworkRateLimit = 18,
    SetConnectionLimit = 19,
    SetRequestsPerSecondLimit = 20,
    RunEdgeScript = 21,
    OriginMagicContainers = 22,
    DisableWaf = 23,
    RetryOrigin = 24,
    OverrideBrowserCacheResponseHeader = 25,
    RemoveBrowserCacheResponseHeader = 26,
    DisableShieldChallenge = 27,
    DisableShield = 28,
    DisableShieldBotDetection = 29,
    BypassAwsS3Authentication = 30,
    DisableShieldAccessLists = 31,
    DisableShieldRateLimiting = 32,
    EnableRequestCoalescing = 33,
    DisableRequestCoalescing = 34,
    StripCookiesClientToOrigin = 37,
}
