//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// GoogleWidevineDrmUpdateModel from OpenAPI schema.
/// Schema path: #/components/schemas/GoogleWidevineDrmUpdateModel
/// </summary>
public partial class GoogleWidevineDrmUpdateModel
{
  /// <summary>
  /// (Optional) Enables or disables Google Widevine Enterprise DRM
  /// </summary>
  public bool? Enabled { get; set; }

  /// <summary>
  /// (Optional) Only allow audio and SD access to Widevine L3 clients
  /// </summary>
  public bool? SdOnlyForL3 { get; set; }

  /// <summary>
  /// (Optional) Minimum Client Security Level (1 being most secure, 3 least secure and is default)
  /// </summary>
  public WidevineMinClientSecurityLevel? MinClientSecurityLevel { get; set; }
}
