//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// GoogleWidevineDrm from OpenAPI schema.
/// Schema path: #/components/schemas/GoogleWidevineDrm
/// </summary>
public partial class GoogleWidevineDrm
{
  public bool? Enabled { get; set; }

  public long? CertificateId { get; set; }

  public DateTimeOffset? CertificateExpirationDate { get; set; }

  public string? Provider { get; set; }

  public bool? SdOnlyForL3 { get; set; }

  public object? MinClientSecurityLevel { get; set; }
}
