//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = IPv4Only
/// 1 = DualStack
/// 2 = DualStackPreferIPv6
/// 3 = IPv6Only
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<IpFamilyPolicy>))]
public enum IpFamilyPolicy
{
    IPv4Only = 0,
    DualStack = 1,
    DualStackPreferIPv6 = 2,
    IPv6Only = 3,
}
