//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// OriginShieldConcurrencyStatisticsModel from OpenAPI schema.
/// Schema path: #/components/schemas/OriginShieldConcurrencyStatisticsModel
/// </summary>
public partial class OriginShieldConcurrencyStatisticsModel
{
  /// <summary>
  /// The constructed chart of origin shield concurrent requests
  /// </summary>
  public Dictionary<string, long>? ConcurrentRequestsChart { get; set; }

  /// <summary>
  /// The constructed chart of origin shield requests chart
  /// </summary>
  public Dictionary<string, long>? QueuedRequestsChart { get; set; }
}
