//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = Automatic
/// 1 = Manual
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<PermaCacheType>))]
public enum PermaCacheType
{
    Automatic = 0,
    Manual = 1,
}
