//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// PriceEstimationModel from OpenAPI schema.
/// Schema path: #/components/schemas/PriceEstimationModel
/// </summary>
public partial class PriceEstimationModel
{
  /// <summary>
  /// 0 = ListPrice
  /// 1 = UserOverride
  /// 2 = ResourceOverride
  /// </summary>
  public AppliedPricingType? PricingType { get; set; }

  public decimal? PricePerUnit { get; set; }

  public string? UnitDescription { get; set; }

  public decimal? EstimatedCost { get; set; }

  public List<PriceEstimationBreakdownLine>? Breakdown { get; set; }
}
