using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 1101 = CDN_Standard_Tier_EU_Traffic
/// 1102 = CDN_Standard_Tier_NA_Traffic
/// 1103 = CDN_Standard_Tier_APAC_Traffic
/// 1104 = CDN_Standard_Tier_AF_Traffic
/// 1105 = CDN_Standard_Tier_SA_Traffic
/// 1106 = CDN_Standard_Tier_Uncategorized
/// 1201 = CDN_Standard_Tier_Stream_EU_Traffic
/// 1202 = CDN_Standard_Tier_Stream_NA_Traffic
/// 1203 = CDN_Standard_Tier_Stream_APAC_Traffic
/// 1204 = CDN_Standard_Tier_Stream_AF_Traffic
/// 1205 = CDN_Standard_Tier_Stream_SA_Traffic
/// 1206 = CDN_Standard_Tier_Stream_Uncategorized
/// 1301 = CDN_Volume_Tier_EU_Traffic
/// 1302 = CDN_Volume_Tier_NA_Traffic
/// 1303 = CDN_Volume_Tier_APAC_Traffic
/// 1304 = CDN_Volume_Tier_AF_Traffic
/// 1305 = CDN_Volume_Tier_SA_Traffic
/// 1306 = CDN_Volume_Tier_Uncategorized
/// 1401 = CDN_Volume_Tier_Stream_EU_Traffic
/// 1402 = CDN_Volume_Tier_Stream_NA_Traffic
/// 1403 = CDN_Volume_Tier_Stream_APAC_Traffic
/// 1404 = CDN_Volume_Tier_Stream_AF_Traffic
/// 1405 = CDN_Volume_Tier_Stream_SA_Traffic
/// 1406 = CDN_Volume_Tier_Stream_Uncategorized
/// 1501 = CDN_Standard_Tier_Storage_EU_Traffic
/// 1502 = CDN_Standard_Tier_Storage_NA_Traffic
/// 1503 = CDN_Standard_Tier_Storage_APAC_Traffic
/// 1504 = CDN_Standard_Tier_Storage_AF_Traffic
/// 1505 = CDN_Standard_Tier_Storage_SA_Traffic
/// 1506 = CDN_Standard_Tier_Storage_Uncategorized
/// 1511 = CDN_Volume_Tier_Storage_EU_Traffic
/// 1512 = CDN_Volume_Tier_Storage_NA_Traffic
/// 1513 = CDN_Volume_Tier_Storage_APAC_Traffic
/// 1514 = CDN_Volume_Tier_Storage_AF_Traffic
/// 1515 = CDN_Volume_Tier_Storage_SA_Traffic
/// 1516 = CDN_Volume_Tier_Storage_Uncategorized
/// 1630 = CDN_WebSockets_ConsumptionBased
/// 1701 = CDN_Standard_Tier_MagicContainers_EU_Traffic
/// 1702 = CDN_Standard_Tier_MagicContainers_NA_Traffic
/// 1703 = CDN_Standard_Tier_MagicContainers_APAC_Traffic
/// 1704 = CDN_Standard_Tier_MagicContainers_AF_Traffic
/// 1705 = CDN_Standard_Tier_MagicContainers_SA_Traffic
/// 1706 = CDN_Standard_Tier_MagicContainers_Uncategorized
/// 1711 = CDN_Volume_Tier_MagicContainers_EU_Traffic
/// 1712 = CDN_Volume_Tier_MagicContainers_NA_Traffic
/// 1713 = CDN_Volume_Tier_MagicContainers_APAC_Traffic
/// 1714 = CDN_Volume_Tier_MagicContainers_AF_Traffic
/// 1715 = CDN_Volume_Tier_MagicContainers_SA_Traffic
/// 1716 = CDN_Volume_Tier_MagicContainers_Uncategorized
/// 1801 = CDN_Standard_Tier_Scripting_EU_Traffic
/// 1802 = CDN_Standard_Tier_Scripting_NA_Traffic
/// 1803 = CDN_Standard_Tier_Scripting_APAC_Traffic
/// 1804 = CDN_Standard_Tier_Scripting_AF_Traffic
/// 1805 = CDN_Standard_Tier_Scripting_SA_Traffic
/// 1806 = CDN_Standard_Tier_Scripting_Uncategorized
/// 1811 = CDN_Volume_Tier_Scripting_EU_Traffic
/// 1812 = CDN_Volume_Tier_Scripting_NA_Traffic
/// 1813 = CDN_Volume_Tier_Scripting_APAC_Traffic
/// 1814 = CDN_Volume_Tier_Scripting_AF_Traffic
/// 1815 = CDN_Volume_Tier_Scripting_SA_Traffic
/// 1816 = CDN_Volume_Tier_Scripting_Uncategorized
/// 2100 = Storage_Standard_Tier
/// 2200 = Storage_SSD_Tier
/// 2300 = Storage_Standard_Tier_Stream
/// 2400 = Storage_SSD_Tier_Stream
/// 4100 = Transcribing
/// 4200 = PremiumEncoding
/// 4300 = DRM_Base
/// 4400 = DRM_LicenseIssued
/// 4501 = LiveEncoding_SD
/// 4502 = LiveEncoding_HD
/// 4503 = LiveEncoding_4K
/// 5200 = Scripting_CDN_Requests
/// 5300 = Scripting_CDN_CPU
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<PricingEstimationSource>))]
public enum PricingEstimationSource
{
    CdnStandardTierEUTraffic = 1101,
    CdnStandardTierNATraffic = 1102,
    CdnStandardTierApacTraffic = 1103,
    CdnStandardTierAFTraffic = 1104,
    CdnStandardTierSATraffic = 1105,
    CdnStandardTierUncategorized = 1106,
    CdnStandardTierStreamEUTraffic = 1201,
    CdnStandardTierStreamNATraffic = 1202,
    CdnStandardTierStreamApacTraffic = 1203,
    CdnStandardTierStreamAFTraffic = 1204,
    CdnStandardTierStreamSATraffic = 1205,
    CdnStandardTierStreamUncategorized = 1206,
    CdnVolumeTierEUTraffic = 1301,
    CdnVolumeTierNATraffic = 1302,
    CdnVolumeTierApacTraffic = 1303,
    CdnVolumeTierAFTraffic = 1304,
    CdnVolumeTierSATraffic = 1305,
    CdnVolumeTierUncategorized = 1306,
    CdnVolumeTierStreamEUTraffic = 1401,
    CdnVolumeTierStreamNATraffic = 1402,
    CdnVolumeTierStreamApacTraffic = 1403,
    CdnVolumeTierStreamAFTraffic = 1404,
    CdnVolumeTierStreamSATraffic = 1405,
    CdnVolumeTierStreamUncategorized = 1406,
    CdnStandardTierStorageEUTraffic = 1501,
    CdnStandardTierStorageNATraffic = 1502,
    CdnStandardTierStorageApacTraffic = 1503,
    CdnStandardTierStorageAFTraffic = 1504,
    CdnStandardTierStorageSATraffic = 1505,
    CdnStandardTierStorageUncategorized = 1506,
    CdnVolumeTierStorageEUTraffic = 1511,
    CdnVolumeTierStorageNATraffic = 1512,
    CdnVolumeTierStorageApacTraffic = 1513,
    CdnVolumeTierStorageAFTraffic = 1514,
    CdnVolumeTierStorageSATraffic = 1515,
    CdnVolumeTierStorageUncategorized = 1516,
    CdnWebSocketsConsumptionBased = 1630,
    CdnStandardTierMagicContainersEUTraffic = 1701,
    CdnStandardTierMagicContainersNATraffic = 1702,
    CdnStandardTierMagicContainersApacTraffic = 1703,
    CdnStandardTierMagicContainersAFTraffic = 1704,
    CdnStandardTierMagicContainersSATraffic = 1705,
    CdnStandardTierMagicContainersUncategorized = 1706,
    CdnVolumeTierMagicContainersEUTraffic = 1711,
    CdnVolumeTierMagicContainersNATraffic = 1712,
    CdnVolumeTierMagicContainersApacTraffic = 1713,
    CdnVolumeTierMagicContainersAFTraffic = 1714,
    CdnVolumeTierMagicContainersSATraffic = 1715,
    CdnVolumeTierMagicContainersUncategorized = 1716,
    CdnStandardTierScriptingEUTraffic = 1801,
    CdnStandardTierScriptingNATraffic = 1802,
    CdnStandardTierScriptingApacTraffic = 1803,
    CdnStandardTierScriptingAFTraffic = 1804,
    CdnStandardTierScriptingSATraffic = 1805,
    CdnStandardTierScriptingUncategorized = 1806,
    CdnVolumeTierScriptingEUTraffic = 1811,
    CdnVolumeTierScriptingNATraffic = 1812,
    CdnVolumeTierScriptingApacTraffic = 1813,
    CdnVolumeTierScriptingAFTraffic = 1814,
    CdnVolumeTierScriptingSATraffic = 1815,
    CdnVolumeTierScriptingUncategorized = 1816,
    StorageStandardTier = 2100,
    StorageSsdTier = 2200,
    StorageStandardTierStream = 2300,
    StorageSsdTierStream = 2400,
    Transcribing = 4100,
    PremiumEncoding = 4200,
    DrmBase = 4300,
    DrmLicenseIssued = 4400,
    LiveEncodingSD = 4501,
    LiveEncodingHD = 4502,
    LiveEncoding4K = 4503,
    ScriptingCdnRequests = 5200,
    ScriptingCdnCpu = 5300,
}
