//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// PullZoneOptimizerClassModel from OpenAPI schema.
/// Schema path: #/components/schemas/PullZoneOptimizerClassModel
/// </summary>
public partial class PullZoneOptimizerClassModel
{
  /// <summary>
  /// The name of the optimizer class that will be used in the query string
  /// </summary>
  public string? Name { get; set; }

  /// <summary>
  /// The list of settings and values the class will send to the optimizer
  /// </summary>
  public Dictionary<string, string?>? Properties { get; set; }
}
