//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// PullZoneModel from OpenAPI schema.
/// Schema path: #/components/schemas/PullZoneModel
/// </summary>
public partial class PullZoneModel
{
  /// <summary>
  /// The unique ID of the pull zone.
  /// </summary>
  public long? Id { get; set; }

  /// <summary>
  /// The name of the pull zone.
  /// </summary>
  public string? Name { get; set; }

  /// <summary>
  /// The origin URL of the pull zone where the files are fetched from.
  /// </summary>
  public string? OriginUrl { get; set; }

  /// <summary>
  /// True unless reached resource limits or account owning it ran out of funds.
  /// </summary>
  public bool? Enabled { get; set; }

  public bool? Suspended { get; set; }

  /// <summary>
  /// The list of hostnames linked to this Pull Zone
  /// </summary>
  public List<HostnameModel>? Hostnames { get; set; }

  /// <summary>
  /// The ID of the storage zone that the pull zone is linked to
  /// </summary>
  public long? StorageZoneId { get; set; }

  /// <summary>
  /// The ID of the edge script that the pull zone is linked to
  /// </summary>
  public long? EdgeScriptId { get; set; }

  /// <summary>
  /// The phase of the request where the script will be executed
  /// </summary>
  public object? EdgeScriptExecutionPhase { get; set; }

  public long? MiddlewareScriptId { get; set; }

  /// <summary>
  /// The ID of the Magic Container application the pull zone is linked to
  /// </summary>
  public string? MagicContainersAppId { get; set; }

  /// <summary>
  /// The ID of the Magic Container Endpoint the pull zone is linked to
  /// </summary>
  public string? MagicContainersEndpointId { get; set; }

  /// <summary>
  /// The list of referrer hostnames that are allowed to access the pull zone.Requests containing the header Referer: hostname that is not on the list will be rejected.If empty, all the referrers are allowed
  /// </summary>
  public List<string?>? AllowedReferrers { get; set; }

  /// <summary>
  /// The list of referrer hostnames that are allowed to access the pull zone. Requests containing the header Referer: hostname that is not on the list will be rejected. If empty, all the referrers are allowed
  /// </summary>
  public List<string?>? BlockedReferrers { get; set; }

  /// <summary>
  /// The list of IPs that are blocked from accessing the pull zone. Requests coming from the following IPs will be rejected. If empty, all the IPs will be allowed
  /// </summary>
  public List<string?>? BlockedIps { get; set; }

  /// <summary>
  /// Determines if the delivery from the North American region is enabled for this pull zone
  /// </summary>
  public bool? EnableGeoZoneUS { get; set; }

  /// <summary>
  /// Determines if the delivery from the European region is enabled for this pull zone
  /// </summary>
  public bool? EnableGeoZoneEU { get; set; }

  /// <summary>
  /// Determines if the delivery from the Asian / Oceanian region is enabled for this pull zone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableGeoZoneASIA")]
  public bool? EnableGeoZoneAsia { get; set; }

  /// <summary>
  /// Determines if the delivery from the South American region is enabled for this pull zone
  /// </summary>
  public bool? EnableGeoZoneSA { get; set; }

  /// <summary>
  /// Determines if the delivery from the Africa region is enabled for this pull zone
  /// </summary>
  public bool? EnableGeoZoneAF { get; set; }

  /// <summary>
  /// Address-family policy: 0=IPv4Only, 1=DualStack, 2=DualStackPreferIPv6, 3=IPv6Only.
  /// </summary>
  public object? IpFamilyPolicy { get; set; }

  /// <summary>
  /// True if the URL secure token authentication security is enabled
  /// </summary>
  public bool? ZoneSecurityEnabled { get; set; }

  /// <summary>
  /// The security key used for secure URL token authentication
  /// </summary>
  public string? ZoneSecurityKey { get; set; }

  /// <summary>
  /// True if the zone security hash should include the remote IP
  /// </summary>
  public bool? ZoneSecurityIncludeHashRemoteIP { get; set; }

  /// <summary>
  /// True if the Pull Zone is ignoring query strings when serving cached objects
  /// </summary>
  public bool? IgnoreQueryStrings { get; set; }

  /// <summary>
  /// The monthly limit of bandwidth in bytes that the pullzone is allowed to use
  /// </summary>
  public long? MonthlyBandwidthLimit { get; set; }

  /// <summary>
  /// The amount of bandwidth in bytes that the pull zone used this month
  /// </summary>
  public long? MonthlyBandwidthUsed { get; set; }

  /// <summary>
  /// The total monthly charges for this so zone so far
  /// </summary>
  public decimal? MonthlyCharges { get; set; }

  /// <summary>
  /// Determines if the Pull Zone should forward the current hostname to the origin
  /// </summary>
  public bool? AddHostHeader { get; set; }

  /// <summary>
  /// Determines the host header that will be sent to the origin
  /// </summary>
  public string? OriginHostHeader { get; set; }

  /// <summary>
  /// The type of the pull zone. Premium = 0, Volume = 1
  /// </summary>
  public object? Type { get; set; }

  /// <summary>
  /// The list of extensions that will return the CORS headers
  /// </summary>
  public List<string?>? AccessControlOriginHeaderExtensions { get; set; }

  /// <summary>
  /// Determines if the CORS headers should be enabled
  /// </summary>
  public bool? EnableAccessControlOriginHeader { get; set; }

  /// <summary>
  /// Determines if the cookies are disabled for the pull zone
  /// </summary>
  public bool? DisableCookies { get; set; }

  /// <summary>
  /// The list of budget redirected countries with the two-letter Alpha2 ISO codes
  /// </summary>
  public List<string?>? BudgetRedirectedCountries { get; set; }

  /// <summary>
  /// The list of blocked countries with the two-letter Alpha2 ISO codes
  /// </summary>
  public List<string?>? BlockedCountries { get; set; }

  /// <summary>
  /// If true the server will use the origin shield feature
  /// </summary>
  public bool? EnableOriginShield { get; set; }

  /// <summary>
  /// The override cache time for the pull zone
  /// </summary>
  public long? CacheControlMaxAgeOverride { get; set; }

  /// <summary>
  /// The override cache time for the pull zone for the end client
  /// </summary>
  public long? CacheControlPublicMaxAgeOverride { get; set; }

  /// <summary>
  /// Excessive requests are delayed until their number exceeds the maximum burst size.
  /// </summary>
  public int? BurstSize { get; set; }

  /// <summary>
  /// Max number of requests per IP per second
  /// </summary>
  public int? RequestLimit { get; set; }

  /// <summary>
  /// If true, access to root path will return a 403 error
  /// </summary>
  public bool? BlockRootPathAccess { get; set; }

  /// <summary>
  /// If true, POST requests to the zone will be blocked
  /// </summary>
  public bool? BlockPostRequests { get; set; }

  /// <summary>
  /// The maximum rate at which the zone will transfer data in kb/s. 0 for unlimited
  /// </summary>
  public double? LimitRatePerSecond { get; set; }

  /// <summary>
  /// The amount of data after the rate limit will be activated
  /// </summary>
  public double? LimitRateAfter { get; set; }

  /// <summary>
  /// The number of connections limited per IP for this zone
  /// </summary>
  public int? ConnectionLimitPerIPCount { get; set; }

  /// <summary>
  /// The custom price override for this zone. Unit is $/Byte.
  /// </summary>
  public decimal? PriceOverride { get; set; }

  /// <summary>
  /// Monthly pricing for Bunny Optimizer for this pull zone
  /// </summary>
  public decimal? OptimizerPricing { get; set; }

  /// <summary>
  /// Determines if the Add Canonical Header is enabled for this Pull Zone
  /// </summary>
  public bool? AddCanonicalHeader { get; set; }

  /// <summary>
  /// Determines if the logging is enabled for this Pull Zone
  /// </summary>
  public bool? EnableLogging { get; set; }

  /// <summary>
  /// Determines if the cache slice (Optimize for video) feature is enabled for the Pull Zone
  /// </summary>
  public bool? EnableCacheSlice { get; set; }

  /// <summary>
  /// Determines if smart caching is enabled for this zone
  /// </summary>
  public bool? EnableSmartCache { get; set; }

  /// <summary>
  /// The list of edge rules on this Pull Zone
  /// </summary>
  public List<EdgeRuleV2Model>? EdgeRules { get; set; }

  /// <summary>
  /// Determines if the WebP Vary feature is enabled.
  /// </summary>
  public bool? EnableWebPVary { get; set; }

  /// <summary>
  /// Determines if the AVIF Vary feature is enabled.
  /// </summary>
  public bool? EnableAvifVary { get; set; }

  /// <summary>
  /// Determines if the Country Code Vary feature is enabled.
  /// </summary>
  public bool? EnableCountryCodeVary { get; set; }

  /// <summary>
  /// Determines if the Country State Code Vary feature should be enabled.
  /// </summary>
  public bool? EnableCountryStateCodeVary { get; set; }

  /// <summary>
  /// Determines if the Mobile Vary feature is enabled.
  /// </summary>
  public bool? EnableMobileVary { get; set; }

  /// <summary>
  /// Determines if the Cookie Vary feature is enabled.
  /// </summary>
  public bool? EnableCookieVary { get; set; }

  /// <summary>
  /// Contains the list of vary parameters that will be used for vary cache by cookie string. If empty, cookie vary will not be used.
  /// </summary>
  public List<string?>? CookieVaryParameters { get; set; }

  /// <summary>
  /// Determines if the Hostname Vary feature is enabled.
  /// </summary>
  public bool? EnableHostnameVary { get; set; }

  /// <summary>
  /// The CNAME domain of the pull zone for setting up custom hostnames
  /// </summary>
  public string? CnameDomain { get; set; }

  /// <summary>
  /// Determines if the AWS Signing is enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("AWSSigningEnabled")]
  public bool? AwsSigningEnabled { get; set; }

  /// <summary>
  /// The AWS Signing region key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("AWSSigningKey")]
  public string? AwsSigningKey { get; set; }

  /// <summary>
  /// The AWS Signing region secret
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("AWSSigningSecret")]
  public string? AwsSigningSecret { get; set; }

  /// <summary>
  /// The AWS Signing region name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("AWSSigningRegionName")]
  public string? AwsSigningRegionName { get; set; }

  /// <summary>
  /// Determines if the TLS 1 is enabled on the Pull Zone
  /// </summary>
  public bool? LoggingIPAnonymizationEnabled { get; set; }

  /// <summary>
  /// Determines if the TLS 1 is enabled on the Pull Zone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableTLS1")]
  public bool? EnableTls1 { get; set; }

  /// <summary>
  /// Determines if the TLS 1.1 is enabled on the Pull Zone
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableTLS1_1")]
  public bool? EnableTls11 { get; set; }

  /// <summary>
  /// The minimum TLS security level enforced on the Pull Zone (Legacy = 0, Compatible = 1, ModernOnly = 2)
  /// </summary>
  public object? TlsSecurityLevel { get; set; }

  /// <summary>
  /// Determines if the Pull Zone should verify the origin SSL certificate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("VerifyOriginSSL")]
  public bool? VerifyOriginSsl { get; set; }

  /// <summary>
  /// Determines if custom error page code should be enabled.
  /// </summary>
  public bool? ErrorPageEnableCustomCode { get; set; }

  /// <summary>
  /// Contains the custom error page code that will be returned
  /// </summary>
  public string? ErrorPageCustomCode { get; set; }

  /// <summary>
  /// Determines if the statuspage widget should be displayed on the error pages
  /// </summary>
  public bool? ErrorPageEnableStatuspageWidget { get; set; }

  /// <summary>
  /// The statuspage code that will be used to build the status widget
  /// </summary>
  public string? ErrorPageStatuspageCode { get; set; }

  /// <summary>
  /// Determines if the error pages should be whitelabel or not
  /// </summary>
  public bool? ErrorPageWhitelabel { get; set; }

  /// <summary>
  /// The zone code of the origin shield
  /// </summary>
  public string? OriginShieldZoneCode { get; set; }

  /// <summary>
  /// Determines if the log forawrding is enabled
  /// </summary>
  public bool? LogForwardingEnabled { get; set; }

  /// <summary>
  /// The log forwarding hostname
  /// </summary>
  public string? LogForwardingHostname { get; set; }

  /// <summary>
  /// The log forwarding port
  /// </summary>
  public int? LogForwardingPort { get; set; }

  /// <summary>
  /// The log forwarding token value
  /// </summary>
  public string? LogForwardingToken { get; set; }

  /// <summary>
  /// Determines the log forwarding protocol type
  /// </summary>
  public object? LogForwardingProtocol { get; set; }

  /// <summary>
  /// Determines if the permanent logging feature is enabled
  /// </summary>
  public bool? LoggingSaveToStorage { get; set; }

  /// <summary>
  /// The ID of the logging storage zone that is configured for this Pull Zone
  /// </summary>
  public long? LoggingStorageZoneId { get; set; }

  /// <summary>
  /// Determines if the zone will follow origin redirects
  /// </summary>
  public bool? FollowRedirects { get; set; }

  /// <summary>
  /// The ID of the video library that the zone is linked to
  /// </summary>
  public long? VideoLibraryId { get; set; }

  /// <summary>
  /// The ID of the DNS record tied to this pull zone
  /// </summary>
  public long? DnsRecordId { get; set; }

  /// <summary>
  /// The ID of the DNS zone tied to this pull zone
  /// </summary>
  public long? DnsZoneId { get; set; }

  /// <summary>
  /// The cached version of the DNS record value
  /// </summary>
  public string? DnsRecordValue { get; set; }

  /// <summary>
  /// Determines if the optimizer should be enabled for this zone
  /// </summary>
  public bool? OptimizerEnabled { get; set; }

  /// <summary>
  /// Determines if the optimizer origin tunnel system is enabled for this zone
  /// </summary>
  public bool? OptimizerTunnelEnabled { get; set; }

  /// <summary>
  /// Determines if the optimizer tunnel system active probing should be enabled for this zone
  /// </summary>
  public bool? OptimizerTunnelActiveProbingEnabled { get; set; }

  /// <summary>
  /// Determines the maximum automatic image size for desktop clients
  /// </summary>
  [Range(0.0, 5000.0)]
  public int? OptimizerDesktopMaxWidth { get; set; }

  /// <summary>
  /// Determines the maximum automatic image size for mobile clients
  /// </summary>
  [Range(0.0, 5000.0)]
  public int? OptimizerMobileMaxWidth { get; set; }

  /// <summary>
  /// Determines the image quality for desktop clients
  /// </summary>
  [Range(1.0, 100.0)]
  public int? OptimizerImageQuality { get; set; }

  /// <summary>
  /// Determines the image quality for mobile clients
  /// </summary>
  [Range(1.0, 100.0)]
  public int? OptimizerMobileImageQuality { get; set; }

  /// <summary>
  /// Determines if the WebP optimization should be enabled
  /// </summary>
  public bool? OptimizerEnableWebP { get; set; }

  /// <summary>
  /// Determines if the SEO HTML prerender is enabled
  /// </summary>
  public bool? OptimizerPrerenderHtml { get; set; }

  /// <summary>
  /// Determines if Markdown automatic generation for AI systems is enabled and which pipeline to use
  /// </summary>
  public object? OptimizerHtmlToMarkdown { get; set; }

  /// <summary>
  /// Determines if the llms.txt file can be generated and served by the Optimizer
  /// </summary>
  public bool? OptimizerLlmsTxt { get; set; }

  /// <summary>
  /// Determines the image manipulation should be enabled
  /// </summary>
  public bool? OptimizerEnableManipulationEngine { get; set; }

  /// <summary>
  /// Determines if the CSS minifcation should be enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("OptimizerMinifyCSS")]
  public bool? OptimizerMinifyCss { get; set; }

  /// <summary>
  /// Determines if the JavaScript minifcation should be enabled
  /// </summary>
  public bool? OptimizerMinifyJavaScript { get; set; }

  /// <summary>
  /// Determines if image watermarking should be enabled
  /// </summary>
  public bool? OptimizerWatermarkEnabled { get; set; }

  /// <summary>
  /// Sets the URL of the watermark image
  /// </summary>
  public string? OptimizerWatermarkUrl { get; set; }

  /// <summary>
  /// Sets the position of the watermark image
  /// </summary>
  public object? OptimizerWatermarkPosition { get; set; }

  /// <summary>
  /// Sets the offset of the watermark image
  /// </summary>
  public double? OptimizerWatermarkOffset { get; set; }

  /// <summary>
  /// Sets the minimum image size to which the watermark will be added
  /// </summary>
  public int? OptimizerWatermarkMinImageSize { get; set; }

  /// <summary>
  /// Determines if the automatic image optimization should be enabled
  /// </summary>
  public bool? OptimizerAutomaticOptimizationEnabled { get; set; }

  /// <summary>
  /// The IP of the storage zone used for Perma-Cache
  /// </summary>
  public long? PermaCacheStorageZoneId { get; set; }

  /// <summary>
  /// Determines Perma-Cache behavior
  /// </summary>
  public object? PermaCacheType { get; set; }

  /// <summary>
  /// The number of retries to the origin server
  /// </summary>
  public int? OriginRetries { get; set; }

  /// <summary>
  /// The amount of seconds to wait when connecting to the origin. Otherwise the request will fail or retry.
  /// </summary>
  public int? OriginConnectTimeout { get; set; }

  /// <summary>
  /// The amount of seconds to wait when waiting for the origin reply. Otherwise the request will fail or retry.
  /// </summary>
  public int? OriginResponseTimeout { get; set; }

  /// <summary>
  /// Determines if we should use stale cache while cache is updating
  /// </summary>
  public bool? UseStaleWhileUpdating { get; set; }

  /// <summary>
  /// Determines if we should use stale cache while the origin is offline
  /// </summary>
  public bool? UseStaleWhileOffline { get; set; }

  /// <summary>
  /// Determines if we should retry the request in case of a 5XX response.
  /// </summary>
  public bool? OriginRetry5XXResponses { get; set; }

  /// <summary>
  /// Determines if we should retry the request in case of a connection timeout.
  /// </summary>
  public bool? OriginRetryConnectionTimeout { get; set; }

  /// <summary>
  /// Determines if we should retry the request in case of a response timeout.
  /// </summary>
  public bool? OriginRetryResponseTimeout { get; set; }

  /// <summary>
  /// Determines the amount of time that the CDN should wait before retrying an origin request.
  /// </summary>
  public int? OriginRetryDelay { get; set; }

  /// <summary>
  /// Contains the list of vary parameters that will be used for vary cache by query string. If empty, all parameters will be used to construct the key
  /// </summary>
  public List<string?>? QueryStringVaryParameters { get; set; }

  /// <summary>
  /// Determines if the origin shield concurrency limit is enabled.
  /// </summary>
  public bool? OriginShieldEnableConcurrencyLimit { get; set; }

  /// <summary>
  /// Determines the number of maximum concurrent requests allowed to the origin.
  /// </summary>
  public int? OriginShieldMaxConcurrentRequests { get; set; }

  public bool? EnableSafeHop { get; set; }

  /// <summary>
  /// Determines if bunny.net should be caching error responses
  /// </summary>
  public bool? CacheErrorResponses { get; set; }

  /// <summary>
  /// Determines the max queue wait time
  /// </summary>
  public int? OriginShieldQueueMaxWaitTime { get; set; }

  /// <summary>
  /// Determines the max number of origin requests that will remain in the queu
  /// </summary>
  public int? OriginShieldMaxQueuedRequests { get; set; }

  /// <summary>
  /// Contains the list of optimizer classes
  /// </summary>
  public List<OptimizerClassModel>? OptimizerClasses { get; set; }

  /// <summary>
  /// Determines if the optimizer class list should be enforced
  /// </summary>
  public bool? OptimizerForceClasses { get; set; }

  /// <summary>
  /// Determines whether optimizer static html feature enabled
  /// </summary>
  public bool? OptimizerStaticHtmlEnabled { get; set; }

  /// <summary>
  /// Wordpress html path which should be bypassed by permacache in edge rule
  /// </summary>
  public string? OptimizerStaticHtmlWordPressPath { get; set; }

  /// <summary>
  /// Wordpress cookie which should be bypassed by permacache in edge rule
  /// </summary>
  public string? OptimizerStaticHtmlWordPressBypassCookie { get; set; }

  /// <summary>
  /// Determines if cache update is performed in the background.
  /// </summary>
  public bool? UseBackgroundUpdate { get; set; }

  /// <summary>
  /// If set to true, any hostnames added to this Pull Zone will automatically enable SSL.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableAutoSSL")]
  public bool? EnableAutoSsl { get; set; }

  /// <summary>
  /// If set to true the query string ordering property is enabled.
  /// </summary>
  public bool? EnableQueryStringOrdering { get; set; }

  /// <summary>
  /// Gets the log anonymization type for this pull zone
  /// </summary>
  public object? LogAnonymizationType { get; set; }

  /// <summary>
  /// 0 = Plain
  /// 1 = JSON
  /// </summary>
  public PullZoneLogFormat? LogFormat { get; set; }

  /// <summary>
  /// 0 = Plain
  /// 1 = JSON
  /// </summary>
  public PullZoneLogFormat? LogForwardingFormat { get; set; }

  /// <summary>
  /// 0 = DetectOnly
  /// 1 = ActiveStandard
  /// 2 = ActiveAggressive
  /// </summary>
  public ShieldDDosProtectionType? ShieldDDosProtectionType { get; set; }

  public bool? ShieldDDosProtectionEnabled { get; set; }

  /// <summary>
  /// The type of the origin for this Pull Zone
  /// </summary>
  public object? OriginType { get; set; }

  /// <summary>
  /// Determines if request coalescing is currently enabled.
  /// </summary>
  public bool? EnableRequestCoalescing { get; set; }

  /// <summary>
  /// Determines the lock time for coalesced requests.
  /// </summary>
  public int? RequestCoalescingTimeout { get; set; }

  /// <summary>
  /// Returns the link short preview value for the pull zone origin connection.
  /// </summary>
  public string? OriginLinkValue { get; set; }

  /// <summary>
  /// If true, the built-in let&apos;s encrypt is disabled and requests are passed to the origin.
  /// </summary>
  public bool? DisableLetsEncrypt { get; set; }

  public bool? EnableBunnyImageAi { get; set; }

  public List<BunnyAiImageBlueprintModel>? BunnyAiImageBlueprints { get; set; }

  /// <summary>
  /// Determines if the preloading screen is currently enabled
  /// </summary>
  public bool? PreloadingScreenEnabled { get; set; }

  /// <summary>
  /// Determines if the preloading screen is shown on the first load from a user.
  /// </summary>
  public bool? PreloadingScreenShowOnFirstVisit { get; set; }

  /// <summary>
  /// The custom preloading screen code
  /// </summary>
  public string? PreloadingScreenCode { get; set; }

  /// <summary>
  /// The preloading screen logo URL
  /// </summary>
  public string? PreloadingScreenLogoUrl { get; set; }

  /// <summary>
  /// Determines if the custom preloader screen is enabled
  /// </summary>
  public bool? PreloadingScreenCodeEnabled { get; set; }

  /// <summary>
  /// The currently configured preloading screem theme. (0 - Light, 1 - Dark)
  /// </summary>
  public object? PreloadingScreenTheme { get; set; }

  /// <summary>
  /// The delay in miliseconds after which the preloading screen will be desplayed
  /// </summary>
  public int? PreloadingScreenDelay { get; set; }

  /// <summary>
  /// The Pull Zone specific pricing discount for EU and US region.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EUUSDiscount")]
  public int? EuusDiscount { get; set; }

  /// <summary>
  /// The Pull Zone specific pricing discount for South America region.
  /// </summary>
  public int? SouthAmericaDiscount { get; set; }

  /// <summary>
  /// The Pull Zone specific pricing discount for Africa region.
  /// </summary>
  public int? AfricaDiscount { get; set; }

  /// <summary>
  /// The Pull Zone specific pricing discount for Asia &amp; Oceania region.
  /// </summary>
  public int? AsiaOceaniaDiscount { get; set; }

  /// <summary>
  /// The list of routing filters enabled for this zone
  /// </summary>
  public List<string?>? RoutingFilters { get; set; }

  /// <summary>
  /// Determines if direct access to files will be blocked if not coming from allowed referrers
  /// </summary>
  public bool? BlockNoneReferrer { get; set; }

  /// <summary>
  /// Whether to use a Sticky Session mechanism for this pull zone
  /// </summary>
  public object? StickySessionType { get; set; }

  /// <summary>
  /// Sticky Session Cookie Name
  /// </summary>
  public string? StickySessionCookieName { get; set; }

  /// <summary>
  /// A set of comma-separated header names used to identify clients
  /// </summary>
  public string? StickySessionClientHeaders { get; set; }

  /// <summary>
  /// The ID of the Load Balancer profile used as the origin when OriginType is LoadBalancer
  /// </summary>
  public long? LoadBalancerId { get; set; }

  /// <summary>
  /// User Id of the pull zone owner
  /// </summary>
  public string? UserId { get; set; }

  public long? CacheVersion { get; set; }

  /// <summary>
  /// Determines if Optimizer is allowed to upscale images
  /// </summary>
  public bool? OptimizerEnableUpscaling { get; set; }

  /// <summary>
  /// Determines if WebSocket connections are allowed for this Pull Zone.
  /// </summary>
  public bool? EnableWebSockets { get; set; }

  /// <summary>
  /// The maximum global simultaneous WebSocket connections allowed for this Pull Zone.
  /// </summary>
  public int? MaxWebSocketConnections { get; set; }

  /// <summary>
  /// Determines if extended logging with additional details is enabled for this Pull Zone.
  /// </summary>
  public bool? EnableExtendedLogging { get; set; }

  /// <summary>
  /// Vary Cache by Request Headers (comma delimited)
  /// </summary>
  public string? CacheKeyHeaders { get; set; }
}
