//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = UDP
/// 1 = TCP
/// 2 = TCPEncrypted
/// 3 = DataDog
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<PullZoneLogForwarderProtocolType>))]
public enum PullZoneLogForwarderProtocolType
{
    Udp = 0,
    Tcp = 1,
    TcpEncrypted = 2,
    DataDog = 3,
}
