//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// SafeHopStatisticsModel from OpenAPI schema.
/// Schema path: #/components/schemas/SafeHopStatisticsModel
/// </summary>
public partial class SafeHopStatisticsModel
{
  /// <summary>
  /// The constructed chart of requests retried
  /// </summary>
  public Dictionary<string, long>? RequestsRetriedChart { get; set; }

  /// <summary>
  /// The constructed chart of requests saved
  /// </summary>
  public Dictionary<string, long>? RequestsSavedChart { get; set; }

  /// <summary>
  /// The total number of retried requests
  /// </summary>
  public double? TotalRequestsRetried { get; set; }

  /// <summary>
  /// The total number of saved requests
  /// </summary>
  public double? TotalRequestsSaved { get; set; }
}
