//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// 0 = NotSupported
/// 1 = Supported
/// </summary>
[JsonConverter(typeof(JsonNumberEnumConverter<StorageZoneS3Type>))]
public enum StorageZoneS3Type
{
    NotSupported = 0,
    Supported = 1,
}
