//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// TriggerDnsZoneRecordScanRequest from OpenAPI schema.
/// Schema path: #/components/schemas/TriggerDnsZoneRecordScanRequest
/// </summary>
public partial class TriggerDnsZoneRecordScanRequest
{
  /// <summary>
  /// The ID of the DNS Zone to scan. Either ZoneId or Domain must be provided, but not both.
  /// </summary>
  public long? ZoneId { get; set; }

  /// <summary>
  /// The domain name to scan. Either ZoneId or Domain must be provided, but not both. Can be used even before creating the DNS zone.
  /// </summary>
  public string? Domain { get; set; }
}
