//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// VideoLibraryUpdateModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoLibraryUpdateModel
/// </summary>
public partial class VideoLibraryUpdateModel
{
  /// <summary>
  /// (Optional) Sets name of the video library
  /// </summary>
  public string? Name { get; set; }

  /// <summary>
  /// (Optional) Sets the player custom HTML code
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("CustomHTML")]
  public string? CustomHtml { get; set; }

  /// <summary>
  /// (Optional) Sets the player key control color
  /// </summary>
  public string? PlayerKeyColor { get; set; }

  /// <summary>
  /// (Optional) Determines if the token authentication should be enabled
  /// </summary>
  public bool? EnableTokenAuthentication { get; set; }

  /// <summary>
  /// (Optional) Determines if the token IP verification should be enabled
  /// </summary>
  public bool? EnableTokenIPVerification { get; set; }

  /// <summary>
  /// (Optional) Set to true to reset the CDN and embed view token key
  /// </summary>
  public bool? ResetToken { get; set; }

  /// <summary>
  /// (Optional) Sets the left offset of the watermark position (in %)
  /// </summary>
  public int? WatermarkPositionLeft { get; set; }

  /// <summary>
  /// (Optional) Sets the top offset of the watermark position (in %)
  /// </summary>
  public int? WatermarkPositionTop { get; set; }

  /// <summary>
  /// (Optional) Sets the width of the watermark (in %)
  /// </summary>
  public int? WatermarkWidth { get; set; }

  /// <summary>
  /// (Optional) Sets the height of the watermark (in %)
  /// </summary>
  public int? WatermarkHeight { get; set; }

  /// <summary>
  /// (Optional) Sets the enabled resolutions for the transcoding. At least one resolution should be enabled. Possible values: 240p, 360p, 480p, 720p, 1080p, 1440p, 2160p
  /// </summary>
  public string? EnabledResolutions { get; set; }

  /// <summary>
  /// (Optional) Sets the vi.ai publisher ID
  /// </summary>
  public string? ViAiPublisherId { get; set; }

  /// <summary>
  /// (Optional) Sets the Vast tag URL
  /// </summary>
  public string? VastTagUrl { get; set; }

  /// <summary>
  /// (Optional) Sets the webhook API url
  /// </summary>
  public string? WebhookUrl { get; set; }

  /// <summary>
  /// (Optional) Sets the captions display font size
  /// </summary>
  public int? CaptionsFontSize { get; set; }

  /// <summary>
  /// (Optional) Sets the captions display font color
  /// </summary>
  public string? CaptionsFontColor { get; set; }

  /// <summary>
  /// (Optional) Sets the captions display background color
  /// </summary>
  public string? CaptionsBackground { get; set; }

  /// <summary>
  /// (Optional) Sets the UI language of the video player.
  /// </summary>
  public string? UILanguage { get; set; }

  /// <summary>
  /// (Optional) Determines if the Early-Play feature should be enabled. Enabling this will enable Expose Originals.
  /// </summary>
  public bool? AllowEarlyPlay { get; set; }

  /// <summary>
  /// (Optional) Determines if the token authentication should be enabled.
  /// </summary>
  public bool? PlayerTokenAuthenticationEnabled { get; set; }

  /// <summary>
  /// (Optional) Determines if requests without a referer should be blocked.
  /// </summary>
  public bool? BlockNoneReferrer { get; set; }

  /// <summary>
  /// (Optional) Determines if MP4 fallback should be enabled for this library.
  /// </summary>
  public bool? EnableMP4Fallback { get; set; }

  /// <summary>
  /// (Optional) Determines if the original file should be kept after the video is processed.
  /// </summary>
  public bool? KeepOriginalFiles { get; set; }

  /// <summary>
  /// (Optional) Determines if direct play URLs should be enabled for the library
  /// </summary>
  public bool? AllowDirectPlay { get; set; }

  /// <summary>
  /// (Optional) Determines if MediaCage DRM should be enabled for this library
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableDRM")]
  public bool? EnableDrm { get; set; }

  /// <summary>
  /// (Optional) Determines MediaCage DRM version to be used for this library
  /// </summary>
  public object? DrmVersion { get; set; }

  /// <summary>
  /// (Optional) The comma separated list of controls that will be displayed in the video player. Possible values: play-large, play, progress, current-time, mute, volume, captions, settings, pip, airplay, fullscreen.
  /// </summary>
  public string? Controls { get; set; }

  /// <summary>
  /// (Optional) The comma separated list of playback speeds that will be available in the video player. Possible values: 0.25,0.5,0.75,1.0,1.25,1.5,1.75,2.0,2.5,3,3.5,4
  /// </summary>
  public string? PlaybackSpeeds { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 240p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate240p")]
  public int? Bitrate240P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 360p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate360p")]
  public int? Bitrate360P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 480p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate480p")]
  public int? Bitrate480P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 720p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate720p")]
  public int? Bitrate720P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 1080p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate1080p")]
  public int? Bitrate1080P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 1440p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate1440p")]
  public int? Bitrate1440P { get; set; }

  /// <summary>
  /// (Optional) The bitrate used for encoding 2160p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate2160p")]
  public int? Bitrate2160P { get; set; }

  /// <summary>
  /// (Optional) Determines if the video watch heatmap should be displayed in the player.
  /// </summary>
  public bool? ShowHeatmap { get; set; }

  /// <summary>
  /// (Optional) Determines if content tagging should be enabled for this library.
  /// </summary>
  public bool? EnableContentTagging { get; set; }

  /// <summary>
  /// (Optional) The captions font family.
  /// </summary>
  public string? FontFamily { get; set; }

  /// <summary>
  /// (Optional) Determines if the automatic audio transcribing is currently enabled for this zone.
  /// </summary>
  public bool? EnableTranscribing { get; set; }

  /// <summary>
  /// (Optional) Determines if automatic transcribing title generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingTitleGeneration { get; set; }

  /// <summary>
  /// (Optional) Determines if automatic transcribing description generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingDescriptionGeneration { get; set; }

  /// <summary>
  /// (Optional) Determines if automatic transcribing chapters generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingChaptersGeneration { get; set; }

  /// <summary>
  /// (Optional) Determines if automatic transcribing moments generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingMomentsGeneration { get; set; }

  /// <summary>
  /// (Optional) The list of languages that the captions will be automatically transcribed to.
  /// </summary>
  public List<string?>? TranscribingCaptionLanguages { get; set; }

  /// <summary>
  /// (Optional) Determines if any associated captions will be automatically signaled in the HLS master playlist via EXT-X-MEDIA tags, allowing client players to show captions.
  /// </summary>
  public bool? EnableCaptionsInPlaylist { get; set; }

  /// <summary>
  /// (Optional) Determines if the player will automatically remember the playback position.
  /// </summary>
  public bool? RememberPlayerPosition { get; set; }

  /// <summary>
  /// (Optional) Determines if multiple output audio track support is enabled on video library.
  /// </summary>
  public bool? EnableMultiAudioTrackSupport { get; set; }

  /// <summary>
  /// (Optional) Determines whether output audio stream should be split from video stream segments.
  /// </summary>
  public bool? UseSeparateAudioStream { get; set; }

  /// <summary>
  /// (Optional) Determines whether JIT encoding should be used for the library. Supported in premium encoding only.
  /// </summary>
  public bool? JitEncodingEnabled { get; set; }

  /// <summary>
  /// (Optional) Defines encoding tier to be used with video library. premium is a paid tier that offers either JIT encoding or prioritized encoding and extra codec support.
  /// </summary>
  public object? EncodingTier { get; set; }

  /// <summary>
  /// (Optional) Specifies which video codecs are used for encoding, provided as a comma-separated (CSV) string. Free encoding tier supports only x264. A premium encoding tier adds support for vp9, hevc, and av1.
  /// </summary>
  public string? OutputCodecs { get; set; }

  /// <summary>
  /// (Optional) Configure Apple FairPlay DRM. Works only if Enterprise DRM is set up.
  /// </summary>
  public object? AppleFairPlayDrm { get; set; }

  /// <summary>
  /// (Optional) Configure Google Widevine DRM. Works only if Enterprise DRM is set up.
  /// </summary>
  public object? GoogleWidevineDrm { get; set; }

  /// <summary>
  /// (Optional) Sets player version used for this library
  /// </summary>
  public int? PlayerVersion { get; set; }

  /// <summary>
  /// (Optional) Marks whether all potential video metadata should be removed from the fallback files
  /// </summary>
  public bool? RemoveMetadataFromFallbackVideos { get; set; }

  /// <summary>
  /// (Optional) Marks whether videos should be scaled using both dimensions. Prevents videos being upscaled or unexpected aspect ratio changes.
  /// </summary>
  public bool? ScaleVideoUsingBothDimensions { get; set; }

  /// <summary>
  /// (Optional) Marks whether original video files should be exposed via CDN. Originals are not protected by DRM. Enabling Early-Play will enable this.
  /// </summary>
  public bool? ExposeOriginals { get; set; }

  /// <summary>
  /// (Optional) Marks whether video metadata in form of schema meta tags and LD+JSON should be exposed.
  /// </summary>
  public bool? ExposeVideoMetadata { get; set; }

  /// <summary>
  /// (Optional) Marks whether compact controls should be enabled for the player.
  /// </summary>
  public bool? EnableCompactControls { get; set; }
}
