//
// <auto-generated>
// Bunny Core API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/core.json
// API: bunny.net API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Core.Models;

/// <summary>
/// VideoLibraryModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoLibraryModel
/// </summary>
public partial class VideoLibraryModel
{
  public long? Id { get; set; }

  /// <summary>
  /// The name of the Video Library.
  /// </summary>
  public string? Name { get; set; }

  /// <summary>
  /// The number of videos in the video library
  /// </summary>
  public long? VideoCount { get; set; }

  /// <summary>
  /// The amount of traffic usage this month
  /// </summary>
  public long? TrafficUsage { get; set; }

  /// <summary>
  /// The total amount of storage used by the library
  /// </summary>
  public long? StorageUsage { get; set; }

  /// <summary>
  /// The date when the video library was created
  /// </summary>
  public DateTimeOffset? DateCreated { get; set; }

  /// <summary>
  /// The date when the video library was last modified
  /// </summary>
  public DateTimeOffset? DateModified { get; set; }

  /// <summary>
  /// The geo-replication regions of the underlying storage zone
  /// </summary>
  public List<string?>? ReplicationRegions { get; set; }

  /// <summary>
  /// The API key used for authenticating with the video library
  /// </summary>
  public string? ApiKey { get; set; }

  /// <summary>
  /// The read-only API key used for authenticating with the video library
  /// </summary>
  public string? ReadOnlyApiKey { get; set; }

  /// <summary>
  /// Determines if the video library has a watermark configured
  /// </summary>
  public bool? HasWatermark { get; set; }

  /// <summary>
  /// The left offset of the watermark position (in %)
  /// </summary>
  public int? WatermarkPositionLeft { get; set; }

  /// <summary>
  /// The top offset of the watermark position (in %)
  /// </summary>
  public int? WatermarkPositionTop { get; set; }

  /// <summary>
  /// The width of the watermark (in %)
  /// </summary>
  public int? WatermarkWidth { get; set; }

  /// <summary>
  /// The ID of the connected underlying pull zone
  /// </summary>
  public long? PullZoneId { get; set; }

  /// <summary>
  /// The ID of the connected underlying storage zone
  /// </summary>
  public long? StorageZoneId { get; set; }

  /// <summary>
  /// The height of the watermark (in %)
  /// </summary>
  public int? WatermarkHeight { get; set; }

  /// <summary>
  /// The comma separated list of enabled resolutions
  /// </summary>
  public string? EnabledResolutions { get; set; }

  /// <summary>
  /// The vi.ai publisher id for advertising configuration
  /// </summary>
  public string? ViAiPublisherId { get; set; }

  /// <summary>
  /// The URL of the VAST tag endpoint for advertising configuration
  /// </summary>
  public string? VastTagUrl { get; set; }

  /// <summary>
  /// The webhook URL of the video library
  /// </summary>
  public string? WebhookUrl { get; set; }

  /// <summary>
  /// The captions display font size
  /// </summary>
  public int? CaptionsFontSize { get; set; }

  /// <summary>
  /// The captions display font color
  /// </summary>
  public string? CaptionsFontColor { get; set; }

  /// <summary>
  /// The captions display background color
  /// </summary>
  public string? CaptionsBackground { get; set; }

  /// <summary>
  /// The UI language of the player
  /// </summary>
  public string? UILanguage { get; set; }

  /// <summary>
  /// Determines if the Early-Play feature is enabled
  /// </summary>
  public bool? AllowEarlyPlay { get; set; }

  /// <summary>
  /// Determines if the player token authentication is enabled
  /// </summary>
  public bool? PlayerTokenAuthenticationEnabled { get; set; }

  /// <summary>
  /// The list of allowed referrer domains allowed to access the library
  /// </summary>
  public List<string?>? AllowedReferrers { get; set; }

  /// <summary>
  /// The list of blocked referrer domains blocked from accessing the library
  /// </summary>
  public List<string?>? BlockedReferrers { get; set; }

  /// <summary>
  /// Determines if the requests without a referrer are blocked
  /// </summary>
  public bool? BlockNoneReferrer { get; set; }

  /// <summary>
  /// Determines if the MP4 fallback feature is enabled
  /// </summary>
  public bool? EnableMP4Fallback { get; set; }

  /// <summary>
  /// Determines if the original video files should be stored after encoding
  /// </summary>
  public bool? KeepOriginalFiles { get; set; }

  /// <summary>
  /// Determines direct play URLs are enabled for the library
  /// </summary>
  public bool? AllowDirectPlay { get; set; }

  /// <summary>
  /// Determines if the DRM is enabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("EnableDRM")]
  public bool? EnableDrm { get; set; }

  /// <summary>
  /// DRM version (basic or enterprise)
  /// </summary>
  public object? DrmVersion { get; set; }

  /// <summary>
  /// Described Apple FairPlay DRM
  /// </summary>
  public object? AppleFairPlayDrm { get; set; }

  /// <summary>
  /// Describes Google Widevine DRM
  /// </summary>
  public object? GoogleWidevineDrm { get; set; }

  /// <summary>
  /// The bitrate used for encoding 240p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate240p")]
  public int? Bitrate240P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 360p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate360p")]
  public int? Bitrate360P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 480p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate480p")]
  public int? Bitrate480P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 720p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate720p")]
  public int? Bitrate720P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 1080p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate1080p")]
  public int? Bitrate1080P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 1440p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate1440p")]
  public int? Bitrate1440P { get; set; }

  /// <summary>
  /// The bitrate used for encoding 2160p videos
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("Bitrate2160p")]
  public int? Bitrate2160P { get; set; }

  public string? ApiAccessKey { get; set; }

  /// <summary>
  /// Determines if the video watch heatmap should be displayed in the player.
  /// </summary>
  public bool? ShowHeatmap { get; set; }

  /// <summary>
  /// Determines if content tagging should be enabled for this library.
  /// </summary>
  public bool? EnableContentTagging { get; set; }

  /// <summary>
  /// The type of the pull zone attached. Premium = 0, Volume = 1
  /// </summary>
  public object? PullZoneType { get; set; }

  /// <summary>
  /// The custom HTMl that is added into the head of the HTML player.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("CustomHTML")]
  public string? CustomHtml { get; set; }

  /// <summary>
  /// The list of controls on the video player.
  /// </summary>
  public string? Controls { get; set; }

  /// <summary>
  /// The list of playback speeds available in the video player.
  /// </summary>
  public string? PlaybackSpeeds { get; set; }

  /// <summary>
  /// The key color of the player.
  /// </summary>
  public string? PlayerKeyColor { get; set; }

  /// <summary>
  /// The captions font family.
  /// </summary>
  public string? FontFamily { get; set; }

  public long? WatermarkVersion { get; set; }

  /// <summary>
  /// Determines if the automatic audio transcribing is currently enabled for this zone.
  /// </summary>
  public bool? EnableTranscribing { get; set; }

  /// <summary>
  /// Determines if automatic transcribing title generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingTitleGeneration { get; set; }

  /// <summary>
  /// Determines if automatic transcribing description generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingDescriptionGeneration { get; set; }

  /// <summary>
  /// Determines if automatic transcribing chapters generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingChaptersGeneration { get; set; }

  /// <summary>
  /// Determines if automatic transcribing moments generation is currently enabled.
  /// </summary>
  public bool? EnableTranscribingMomentsGeneration { get; set; }

  /// <summary>
  /// The list of languages that the captions will be automatically transcribed to.
  /// </summary>
  public List<string?>? TranscribingCaptionLanguages { get; set; }

  /// <summary>
  /// Determines if any associated captions will be automatically signaled in the HLS master playlist via EXT-X-MEDIA tags, allowing client players to show captions.
  /// </summary>
  public bool? EnableCaptionsInPlaylist { get; set; }

  /// <summary>
  /// Determines if the player will automatically remember the playback position.
  /// </summary>
  public bool? RememberPlayerPosition { get; set; }

  /// <summary>
  /// Determines if multiple output audio track support is enabled on video library.
  /// </summary>
  public bool? EnableMultiAudioTrackSupport { get; set; }

  /// <summary>
  /// Determines whether output audio stream should be split from video stream segments.
  /// </summary>
  public bool? UseSeparateAudioStream { get; set; }

  /// <summary>
  /// Determines whether JIT encoding should be used for the library. Supported in premium encoding only.
  /// </summary>
  public bool? JitEncodingEnabled { get; set; }

  /// <summary>
  /// Defines encoding tier to be used with video library. premium is a paid tier that offers either JIT encoding or prioritized encoding and extra codec support.
  /// </summary>
  public object? EncodingTier { get; set; }

  /// <summary>
  /// Specifies which video codecs are used for encoding, provided as a comma-separated (CSV) string. Free encoding tier supports only x264. A premium encoding tier adds support for vp9, hevc, and av1.
  /// </summary>
  public string? OutputCodecs { get; set; }

  /// <summary>
  /// DRM (enterprise) monthly base price for this video library if it differs from list price.
  /// </summary>
  public decimal? DrmBasePriceOverride { get; set; }

  /// <summary>
  /// DRM (enterprise) cost per license for this video library if it differs from list price.
  /// </summary>
  public decimal? DrmCostPerLicenseOverride { get; set; }

  public decimal? TranscribingPriceOverride { get; set; }

  public decimal? PremiumEncodingPriceOverride { get; set; }

  public decimal? MonthlyChargesTranscribing { get; set; }

  public decimal? MonthlyChargesPremiumEncoding { get; set; }

  public decimal? MonthlyChargesEnterpriseDrm { get; set; }

  public string? FeatureFlags { get; set; }

  public int? PlayerVersion { get; set; }

  /// <summary>
  /// Marks whether all potential video metadata should be removed from the fallback files. Default false.
  /// </summary>
  public bool? RemoveMetadataFromFallbackVideos { get; set; }

  /// <summary>
  /// Marks whether videos should be scaled using both dimensions. Prevents videos being upscaled or unexpected aspect ratio changes. Default true.
  /// </summary>
  public bool? ScaleVideoUsingBothDimensions { get; set; }

  /// <summary>
  /// Marks whether original video files should be exposed via CDN.
  /// </summary>
  public bool? ExposeOriginals { get; set; }

  /// <summary>
  /// Marks whether video metadata in form of schema meta tags and LD+JSON should be exposed.
  /// </summary>
  public bool? ExposeVideoMetadata { get; set; }

  /// <summary>
  /// Marks whether compact controls should be enabled for the player.
  /// </summary>
  public bool? EnableCompactControls { get; set; }
}
