//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;
using Microsoft.Extensions.Logging;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Client for API Guardian operations
/// </summary>
public partial class ApiGuardianClient : IApiGuardianClient
{
  private readonly HttpClient _httpClient;
  private readonly ILogger? _logger;

  internal ApiGuardianClient(HttpClient httpClient, ILogger? logger = null)
  {
    _httpClient = httpClient;
    _logger = logger;
  }

  /// <summary>
  /// Get the API Guardian configuration and endpoints.
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/api-guardian
  /// </summary>
  public async Task<GetApiGuardianResponse> GetAsync(int shieldZoneId, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "GET", url);
      HttpResponseMessage response = await _httpClient.GetAsync(url, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "GET", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "GET", url, errorBody, null);
        throw new ApiException(response.StatusCode, "GET", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      GetApiGuardianResponse? result = JsonSerializer.Deserialize<GetApiGuardianResponse>(responseContent, JsonConfig.Default);
      return result ?? new GetApiGuardianResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "GET", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "GET", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "GET", url, ex);
      throw;
    }
  }


  /// <summary>
  /// Update the API Guardian configuration (enabled, execution mode, body limit action)
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian
  /// </summary>
  public async Task<UpdateApiGuardianConfigurationResponse> UpdateApiGuardianConfigurationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpdateApiGuardianConfigurationRequest updateApiGuardianConfigurationRequest, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "PATCH", url);
      string json = JsonSerializer.Serialize(updateApiGuardianConfigurationRequest, JsonConfig.Default);
      HttpClientLog.LogTraceRequestBody(_logger, "PATCH", "application/json", json);
      StringContent content = new StringContent(json, Encoding.UTF8, "application/json");
      HttpResponseMessage response = await _httpClient.PatchAsync(url, content, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "PATCH", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "PATCH", url, errorBody, null);
        throw new ApiException(response.StatusCode, "PATCH", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      UpdateApiGuardianConfigurationResponse? result = JsonSerializer.Deserialize<UpdateApiGuardianConfigurationResponse>(responseContent, JsonConfig.Default);
      return result ?? new UpdateApiGuardianConfigurationResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "PATCH", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "PATCH", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "PATCH", url, ex);
      throw;
    }
  }


  /// <summary>
  /// Update your API Guardian Endpoint configuration
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian/endpoint/{endpointId}
  /// </summary>
  public async Task<UpdateApiGuardianEndpointResponse> UpdateApiGuardianEndpointAsync(int shieldZoneId, long endpointId, Apigen.Bunny.Shield.Models.UpdateApiGuardianEndpointRequest updateApiGuardianEndpointRequest, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId,
      ["endpointId"] = endpointId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian/endpoint/{endpointId}".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "PATCH", url);
      string json = JsonSerializer.Serialize(updateApiGuardianEndpointRequest, JsonConfig.Default);
      HttpClientLog.LogTraceRequestBody(_logger, "PATCH", "application/json", json);
      StringContent content = new StringContent(json, Encoding.UTF8, "application/json");
      HttpResponseMessage response = await _httpClient.PatchAsync(url, content, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "PATCH", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "PATCH", url, errorBody, null);
        throw new ApiException(response.StatusCode, "PATCH", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      UpdateApiGuardianEndpointResponse? result = JsonSerializer.Deserialize<UpdateApiGuardianEndpointResponse>(responseContent, JsonConfig.Default);
      return result ?? new UpdateApiGuardianEndpointResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "PATCH", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "PATCH", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "PATCH", url, ex);
      throw;
    }
  }


  /// <summary>
  /// Upload your OpenAPI specification
  /// Operation: POST /shield/shield-zone/{shieldZoneId}/api-guardian/spec
  /// </summary>
  public async Task<UpsertOpenApiSpecificationResponse> UploadOpenApiSpecificationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpsertOpenApiSpecificationRequest upsertOpenApiSpecificationRequest, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian/spec".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "POST", url);
      string json = JsonSerializer.Serialize(upsertOpenApiSpecificationRequest, JsonConfig.Default);
      HttpClientLog.LogTraceRequestBody(_logger, "POST", "application/json", json);
      StringContent content = new StringContent(json, Encoding.UTF8, "application/json");
      HttpResponseMessage response = await _httpClient.PostAsync(url, content, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "POST", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "POST", url, errorBody, null);
        throw new ApiException(response.StatusCode, "POST", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      UpsertOpenApiSpecificationResponse? result = JsonSerializer.Deserialize<UpsertOpenApiSpecificationResponse>(responseContent, JsonConfig.Default);
      return result ?? new UpsertOpenApiSpecificationResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "POST", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "POST", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "POST", url, ex);
      throw;
    }
  }


  /// <summary>
  /// Update your OpenAPI specification
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian/spec
  /// </summary>
  public async Task<UpsertOpenApiSpecificationResponse> UpdateOpenApiSpecificationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpsertOpenApiSpecificationRequest upsertOpenApiSpecificationRequest, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian/spec".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "PATCH", url);
      string json = JsonSerializer.Serialize(upsertOpenApiSpecificationRequest, JsonConfig.Default);
      HttpClientLog.LogTraceRequestBody(_logger, "PATCH", "application/json", json);
      StringContent content = new StringContent(json, Encoding.UTF8, "application/json");
      HttpResponseMessage response = await _httpClient.PatchAsync(url, content, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "PATCH", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "PATCH", url, errorBody, null);
        throw new ApiException(response.StatusCode, "PATCH", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      UpsertOpenApiSpecificationResponse? result = JsonSerializer.Deserialize<UpsertOpenApiSpecificationResponse>(responseContent, JsonConfig.Default);
      return result ?? new UpsertOpenApiSpecificationResponse();
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "PATCH", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "PATCH", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "PATCH", url, ex);
      throw;
    }
  }


  /// <summary>
  /// Get all API Guardian enumeration types and their values
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/api-guardian/enums
  /// </summary>
  public async Task<JsonElement> GetApiGuardianEnumsAsync(string shieldZoneId, CancellationToken cancellationToken = default)
  {
    Dictionary<string, object> pathParams = new()
    {
      ["shieldZoneId"] = shieldZoneId
    };
    string url = "shield/shield-zone/{shieldZoneId}/api-guardian/enums".BuildUrl(pathParams);

    try
    {
      long startTimestamp = System.Diagnostics.Stopwatch.GetTimestamp();
      HttpClientLog.LogDebugRequestStarted(_logger, "GET", url);
      HttpResponseMessage response = await _httpClient.GetAsync(url, cancellationToken);
      long durationMs = (long)System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;
      HttpClientLog.LogDebugRequestCompleted(_logger, (int)response.StatusCode, "GET", url, durationMs);

      if (!response.IsSuccessStatusCode)
      {
        string errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
        HttpClientLog.LogErrorRequestFailed(_logger, (int)response.StatusCode, "GET", url, errorBody, null);
        throw new ApiException(response.StatusCode, "GET", url, errorBody, response.Headers, response.Content.Headers);
      }

      string responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
      HttpClientLog.LogTraceResponseBody(_logger, url, responseContent);
      JsonElement result = JsonSerializer.Deserialize<JsonElement>(responseContent, JsonConfig.Default);
      return result;
    }
    catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
    {
      HttpClientLog.LogDebugRequestCancelled(_logger, "GET", url);
      throw;
    }
    catch (OperationCanceledException ex)
    {
      HttpClientLog.LogErrorRequestTimeout(_logger, "GET", url, ex);
      throw;
    }
    catch (HttpRequestException ex) when (ex is not ApiException)
    {
      HttpClientLog.LogErrorTransportFailure(_logger, "GET", url, ex);
      throw;
    }
  }


}
