//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for Access Lists operations
/// </summary>
public partial interface IAccessListsClient
{
  /// <summary>
  /// Get all Access Lists available for a Shield Zone
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/access-lists
  /// </summary>
  Task<AccessListsDetailsResponse> GetAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a new Custom Access List associated with a Shield Zone
  /// Operation: POST /shield/shield-zone/{shieldZoneId}/access-lists
  /// </summary>
  Task<CustomAccessListResponse> CreateCustomAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.CreateCustomAccessListRequest createCustomAccessListRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Access List Configuration for a Shield Zone
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/access-lists/configurations/{id}
  /// </summary>
  Task<UpdateAccessListConfigurationResponse> UpdateAccessListConfigurationAsync(long id, int shieldZoneId, Apigen.Bunny.Shield.Models.UpdateAccessListConfigurationRequest updateAccessListConfigurationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the specified Custom Access List associated with a Shield Zone
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/access-lists/{id}
  /// </summary>
  Task<CustomAccessListResponse> GetCustomAsync(long id, int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the specified Custom Access List associated with a Shield Zone
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/access-lists/{id}
  /// </summary>
  Task<CustomAccessListResponse> UpdateCustomAsync(long id, int shieldZoneId, Apigen.Bunny.Shield.Models.UpdateCustomAccessListRequest updateCustomAccessListRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the specified Custom Access List associated with a Shield Zone
  /// Operation: DELETE /shield/shield-zone/{shieldZoneId}/access-lists/{id}
  /// </summary>
  Task<GenericRequestResponse> DeleteCustomAsync(long id, int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get all Access Lists API enumeration types and their values
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/access-lists/enums
  /// </summary>
  Task<JsonElement> GetAccessListEnumsAsync(string shieldZoneId, CancellationToken cancellationToken = default);

}
