//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for API Guardian operations
/// </summary>
public partial interface IApiGuardianClient
{
  /// <summary>
  /// Get the API Guardian configuration and endpoints.
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/api-guardian
  /// </summary>
  Task<GetApiGuardianResponse> GetAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the API Guardian configuration (enabled, execution mode, body limit action)
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian
  /// </summary>
  Task<UpdateApiGuardianConfigurationResponse> UpdateApiGuardianConfigurationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpdateApiGuardianConfigurationRequest updateApiGuardianConfigurationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update your API Guardian Endpoint configuration
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian/endpoint/{endpointId}
  /// </summary>
  Task<UpdateApiGuardianEndpointResponse> UpdateApiGuardianEndpointAsync(int shieldZoneId, long endpointId, Apigen.Bunny.Shield.Models.UpdateApiGuardianEndpointRequest updateApiGuardianEndpointRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Upload your OpenAPI specification
  /// Operation: POST /shield/shield-zone/{shieldZoneId}/api-guardian/spec
  /// </summary>
  Task<UpsertOpenApiSpecificationResponse> UploadOpenApiSpecificationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpsertOpenApiSpecificationRequest upsertOpenApiSpecificationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update your OpenAPI specification
  /// Operation: PATCH /shield/shield-zone/{shieldZoneId}/api-guardian/spec
  /// </summary>
  Task<UpsertOpenApiSpecificationResponse> UpdateOpenApiSpecificationAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.UpsertOpenApiSpecificationRequest upsertOpenApiSpecificationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get all API Guardian enumeration types and their values
  /// Operation: GET /shield/shield-zone/{shieldZoneId}/api-guardian/enums
  /// </summary>
  Task<JsonElement> GetApiGuardianEnumsAsync(string shieldZoneId, CancellationToken cancellationToken = default);

}
