//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for DDoS operations
/// </summary>
public partial interface IDDoSClient
{
  /// <summary>
  /// List of all DDoS Enum Mappings
  /// Operation: GET /shield/ddos/enums
  /// </summary>
  Task<GetWafEnumsResponse> GetDDoSEnumsAsync(CancellationToken cancellationToken = default);

}
