//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for Event Logs operations
/// </summary>
public partial interface IEventLogsClient
{
  /// <summary>
  /// Get Event Logs for Shield Zone
  /// Operation: GET /shield/event-logs/{shieldZoneId}/{date}/{continuationToken}
  /// </summary>
  Task<WafLoggingResponse> GetAsync(int shieldZoneId, string date, string continuationToken, CancellationToken cancellationToken = default);

  /// <summary>
  /// Search, filter and group Event Logs for a Shield Zone
  /// Operation: POST /shield/event-logs/{shieldZoneId}/search
  /// </summary>
  Task<EventLogsSearchResponse> SearchAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.EventLogsSearchRequest eventLogsSearchRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Export the full filtered Event Logs set for a Shield Zone as CSV
  /// Operation: POST /shield/event-logs/{shieldZoneId}/export
  /// </summary>
  Task<Stream> ExportAsync(int shieldZoneId, Apigen.Bunny.Shield.Models.EventLogsExportRequest eventLogsExportRequest, CancellationToken cancellationToken = default);

}
