//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for Metrics operations
/// </summary>
public partial interface IMetricsClient
{
  /// <summary>
  /// Get the overage breakdown for the specified Shield Zone for a given month, segmented by billing plan changes
  /// Operation: GET /shield/metrics/overages/{shieldZoneId}
  /// </summary>
  Task<ShieldZoneMonthlyOveragesResult> GetShieldZoneMonthlyOveragesAsync(int shieldZoneId, GetShieldZoneMonthlyOveragesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an overview of metrics for the specified Shield Zone
  /// Operation: GET /shield/metrics/overview/{shieldZoneId}
  /// </summary>
  Task<GetShieldZoneMetricsOverviewResponse> GetShieldZoneMetricsOverviewAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a detailed metrics overview for the specified Shield Zone within the selected time range and resolution
  /// Operation: GET /shield/metrics/overview/{shieldZoneId}/detailed
  /// </summary>
  Task<ShieldOverviewMetrics> GetShieldZoneDetailedMetricsOverviewAsync(int shieldZoneId, GetShieldZoneDetailedMetricsOverviewRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get aggregated rate limit metrics for the specified Shield Zone
  /// Operation: GET /shield/metrics/rate-limits/{shieldZoneId}
  /// </summary>
  Task<GetShieldZoneRatelimitMetricsResponse> GetShieldZoneRateLimitAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get detailed metrics for the specified Rate Limit
  /// Operation: GET /shield/metrics/rate-limit/{id}
  /// </summary>
  Task<GetRatelimitMetricsResponse> GetRateLimitAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get metrics for a specific WAF Rule within the specified Shield Zone
  /// Operation: GET /shield/metrics/shield-zone/{shieldZoneId}/waf-rule/{ruleId}
  /// </summary>
  Task<GetWafRuleMetricsResponse> GetWafRuleAsync(int shieldZoneId, string ruleId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get bot detection metrics for the specified Shield Zone
  /// Operation: GET /shield/metrics/shield-zone/{shieldZoneId}/bot-detection
  /// </summary>
  Task<GetShieldZoneBotDetectionMetricsResponse> GetShieldZoneBotDetectionAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get upload scanning metrics for the specified Shield Zone
  /// Operation: GET /shield/metrics/shield-zone/{shieldZoneId}/upload-scanning
  /// </summary>
  Task<GetShieldZoneUploadScanningMetricsResponse> GetShieldZoneUploadScanningAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get API Guardian metrics for the specified Shield Zone
  /// Operation: GET /shield/metrics/shield-zone/{shieldZoneId}/api-guardian
  /// </summary>
  Task<GetApiGuardianMetricsResponse> GetShieldZoneApiGuardianAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get metrics for a specific API Guardian endpoint within the specified Shield Zone
  /// Operation: GET /shield/metrics/shield-zone/{shieldZoneId}/api-guardian/endpoint/{endpointId}
  /// </summary>
  Task<GetApiGuardianEndpointMetricsResponse> GetApiGuardianEndpointAsync(int shieldZoneId, long endpointId, CancellationToken cancellationToken = default);

}
