//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for Promotions operations
/// </summary>
public partial interface IPromotionsClient
{
  /// <summary>
  /// Get the current Promotion State for your Account
  /// Operation: GET /shield/promo/state
  /// </summary>
  Task GetPromotionStateAsync(CancellationToken cancellationToken = default);

}
