//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for Shield Zone operations
/// </summary>
public partial interface IShieldZoneClient
{
  /// <summary>
  /// Get all of your Shield Zone Configurations
  /// Operation: GET /shield/shield-zones
  /// </summary>
  Task<GetShieldZonesResponse> GetShieldZoneConfigurationsAsync(GetShieldZoneConfigurationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Active Shield Zones for Pullzone Mapping
  /// Operation: GET /shield/shield-zones/pullzone-mapping
  /// </summary>
  Task<GetShieldZonePullzoneMappingResponse> GetShieldZonesPullZoneMappingAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Singular Shield Zone Configuration
  /// Operation: GET /shield/shield-zone/{shieldZoneId}
  /// </summary>
  Task<GetShieldZoneResponse> GetShieldZoneConfigurationAsync(int shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Singular Shield Zone Configuration for PullZone
  /// Operation: GET /shield/shield-zone/get-by-pullzone/{pullZoneId}
  /// </summary>
  Task<GetShieldZoneResponse> GetShieldZoneConfigurationPullZoneAsync(int pullZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the recommended defaults for creating a Shield Zone
  /// Operation: GET /shield/shield-zone/defaults
  /// </summary>
  Task<GetShieldZoneDefaultsResponse> GetShieldZoneDefaultsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Shield Zone in under-attack mode for your PullZone
  /// Operation: POST /shield/shield-zone/under-attack
  /// </summary>
  Task<CreateShieldZoneResponse> CreateShieldZoneUnderAttackAsync(Apigen.Bunny.Shield.Models.CreateUnderAttackShieldZoneRequest createUnderAttackShieldZoneRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Shield Zone for your PullZone
  /// Operation: POST /shield/shield-zone
  /// </summary>
  Task<CreateShieldZoneResponse> CreateAsync(Apigen.Bunny.Shield.Models.CreateShieldZoneRequest createShieldZoneRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update your Shield Zone configuration
  /// Operation: PATCH /shield/shield-zone
  /// </summary>
  Task<UpdateShieldZoneResponse> UpdateAsync(Apigen.Bunny.Shield.Models.UpdateShieldZoneRequest updateShieldZoneRequest, CancellationToken cancellationToken = default);

}
