//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Shield.Models;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Interface for WAF operations
/// </summary>
public partial interface IWafClient
{
  /// <summary>
  /// Retrieve all available WAF rules for a Shield Zone
  /// Operation: GET /shield/waf/rules/{shieldZoneId}
  /// </summary>
  Task<List<WafRuleMainGroupModel>> GetWafRulesAsync(long shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve WAF rules segmented by subscription plan
  /// Operation: GET /shield/waf/rules/plan-segmentation
  /// </summary>
  Task<GetWafRulesSegmentedByPlanResponse> GetWafRulesPlanAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Review all triggered WAF rules for the specified Shield Zone
  /// Operation: GET /shield/waf/rules/review-triggered/{shieldZoneId}
  /// </summary>
  Task<GetTriggeredRulesResponse> GetTriggeredWafRulesAsync(long shieldZoneId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Review and update the action of a triggered WAF rule
  /// Operation: POST /shield/waf/rules/review-triggered/{shieldZoneId}
  /// </summary>
  Task<UpdateReviewTriggeredRuleResponse> UpdateTriggeredWafRuleAsync(long shieldZoneId, Apigen.Bunny.Shield.Models.UpdateReviewTriggeredRuleRequest updateReviewTriggeredRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve an AI recommendation for a triggered WAF rule
  /// Operation: GET /shield/waf/rules/review-triggered/ai-recommendation/{shieldZoneId}/{ruleId}
  /// </summary>
  Task<TriggeredRuleRecommendationResponse> GetTriggeredRuleAIRecommendationAsync(long shieldZoneId, string ruleId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve custom WAF rules configured for the specified Shield Zone
  /// Operation: GET /shield/waf/custom-rules/{shieldZoneId}
  /// </summary>
  Task<GetCustomWafRulesResponse> GetCustomWafRulesAsync(long shieldZoneId, GetCustomWafRulesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve a specific custom WAF rule
  /// Operation: GET /shield/waf/custom-rule/{id}
  /// </summary>
  Task<CustomWafRule> GetCustomWafRuleAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update an existing custom WAF rule
  /// Operation: PUT /shield/waf/custom-rule/{id}
  /// </summary>
  Task<CustomWafRule> UpdateCustomWafRuleAsync(int id, Apigen.Bunny.Shield.Models.UpdateCustomWafRuleRequest updateCustomWafRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update an existing custom WAF rule
  /// Operation: PATCH /shield/waf/custom-rule/{id}
  /// </summary>
  Task<CustomWafRule> PatchShieldWafCustomRuleAsync(int id, Apigen.Bunny.Shield.Models.UpdateCustomWafRuleRequest updateCustomWafRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a custom WAF rule
  /// Operation: DELETE /shield/waf/custom-rule/{id}
  /// </summary>
  Task<GenericRequestResponse> DeleteCustomWafRuleAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a new custom WAF rule
  /// Operation: POST /shield/waf/custom-rule
  /// </summary>
  Task<CustomWafRule> CreateCustomWafRuleAsync(Apigen.Bunny.Shield.Models.CreateCustomWafRuleRequest createCustomWafRuleRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve all available WAF profiles
  /// Operation: GET /shield/waf/profiles
  /// </summary>
  Task<GetWafProfilesResponse> ListWafProfilesAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve all available WAF enum mappings
  /// Operation: GET /shield/waf/enums
  /// </summary>
  Task<GetWafEnumsResponse> GetWafEnumMappingsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Retrieve the default WAF engine configuration
  /// Operation: GET /shield/waf/engine-config
  /// </summary>
  Task<GetWafEngineConfigResponse> GetWafEngineConfigurationAsync(CancellationToken cancellationToken = default);

}
