//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// Application from OpenAPI schema.
/// Schema path: #/components/schemas/Application
/// 
/// Application model
/// </summary>
public partial class Application
{
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Display endpoint model
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("displayEndpoint")]
  public DisplayEndpoint? DisplayEndpoint { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public ApplicationStatus Status { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("runtimeType")]
  public ApplicationRuntimeType RuntimeType { get; set; }

  /// <summary>
  /// Region settings model
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("regionSettings")]
  public RegionSettings RegionSettings { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("containerTemplates")]
  public List<ContainerTemplate>? ContainerTemplates { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("containerInstances")]
  public List<ContainerInstance>? ContainerInstances { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("volumes")]
  public List<VolumeTemplate>? Volumes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("autoScaling")]
  public AutoscalingSettings? AutoScaling { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("networkSettings")]
  public NetworkLimits? NetworkSettings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("repositorySettings")]
  public RepositorySettings? RepositorySettings { get; set; }
}
