//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// ContainerEndpoint from OpenAPI schema.
/// Schema path: #/components/schemas/ContainerEndpoint
/// 
/// Container endpoint model
/// </summary>
public partial class ContainerEndpoint
{
  /// <summary>
  /// Unique endpoint id. Use this value as container_endpoint_id when creating a pull zone that targets this endpoint.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("publicHost")]
  public string? PublicHost { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public EndpointType Type { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isSslEnabled")]
  public bool IsSslEnabled { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("pullZoneId")]
  public string? PullZoneId { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("portMappings")]
  public List<EndpointPortMapping>? PortMappings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("stickySessions")]
  public EndpointStickySession? StickySessions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("internalIpAddresses")]
  public List<EndpointInternalIp>? InternalIpAddresses { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicIpAddresses")]
  public List<EndpointInternalIp>? PublicIpAddresses { get; set; }
}
