//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// ContainerInstance from OpenAPI schema.
/// Schema path: #/components/schemas/ContainerInstance
/// </summary>
public partial class ContainerInstance
{
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("templateId")]
  public string? TemplateId { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("podId")]
  public string? PodId { get; set; }

  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("nodeIpAddress")]
  public string? NodeIpAddress { get; set; }
}
