//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// EndpointPortMapping from OpenAPI schema.
/// Schema path: #/components/schemas/EndpointPortMapping
/// </summary>
public partial class EndpointPortMapping
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("containerPort")]
  public int ContainerPort { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("exposedPort")]
  public int ExposedPort { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("protocols")]
  public List<ProtocolV3>? Protocols { get; set; }
}
