//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// Int32StatusIndicator from OpenAPI schema.
/// Schema path: #/components/schemas/Int32StatusIndicator
/// 
/// Status grade model
/// </summary>
public partial class Int32StatusIndicator
{
  [System.Text.Json.Serialization.JsonPropertyName("indicator")]
  public int? Indicator { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("statusGrade")]
  public Grade? StatusGrade { get; set; }
}
