//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// ListNodesResponse from OpenAPI schema.
/// Schema path: #/components/schemas/ListNodesResponse
/// </summary>
public partial class ListNodesResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("items")]
  public List<string?>? Items { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("meta")]
  public ListMeta? Meta { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cursor")]
  public string? Cursor { get; set; }
}
