//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// OverviewPodVolume from OpenAPI schema.
/// Schema path: #/components/schemas/OverviewPodVolume
/// 
/// One volume of an instance, with both halves of its meter in bytes.
/// </summary>
public partial class OverviewPodVolume
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("usageBytes")]
  public double? UsageBytes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sizeBytes")]
  public double? SizeBytes { get; set; }
}
