//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// OverviewRegion from OpenAPI schema.
/// Schema path: #/components/schemas/OverviewRegion
/// 
/// Overview region model
/// </summary>
public partial class OverviewRegion
{
  [System.Text.Json.Serialization.JsonPropertyName("region")]
  public string? Region { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("isRequired")]
  public bool? IsRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("instances")]
  public int? Instances { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public DeploymentStatus? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("averageCPU")]
  public double? AverageCpu { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("averageRAM")]
  public double? AverageRam { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("averageVolumesUsagePercentage")]
  public double? AverageVolumesUsagePercentage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requests")]
  public double? Requests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("anycastTraffic")]
  public double? AnycastTraffic { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("pods")]
  public List<OverviewPod>? Pods { get; set; }
}
