//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// RepositorySettings from OpenAPI schema.
/// Schema path: #/components/schemas/RepositorySettings
/// </summary>
public partial class RepositorySettings
{
  [System.Text.Json.Serialization.JsonPropertyName("templateRepository")]
  public string? TemplateRepository { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("repositoryName")]
  public string? RepositoryName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public string? Owner { get; set; }
}
