//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// TcpSocketProbeRequestDetails from OpenAPI schema.
/// Schema path: #/components/schemas/TcpSocketProbeRequestDetails
/// </summary>
public partial class TcpSocketProbeRequestDetails
{
  [Range(1, 65535)]
  [System.Text.Json.Serialization.JsonPropertyName("portNumber")]
  public int? PortNumber { get; set; }
}
