//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// UsageSummary from OpenAPI schema.
/// Schema path: #/components/schemas/UsageSummary
/// </summary>
public partial class UsageSummary
{
  [System.Text.Json.Serialization.JsonPropertyName("averageLatency")]
  public double? AverageLatency { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("currentLatency")]
  public double? CurrentLatency { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalVolumeSizeInGb")]
  public double? TotalVolumeSizeInGb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("monthlyCost")]
  public double? MonthlyCost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("latencyChart")]
  public Dictionary<string, double>? LatencyChart { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public ApplicationStatus? Status { get; set; }
}
