//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// ValidationError from OpenAPI schema.
/// Schema path: #/components/schemas/ValidationError
/// </summary>
public partial class ValidationError
{
  [System.Text.Json.Serialization.JsonPropertyName("field")]
  public string? Field { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }
}
