//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// VolumeInList from OpenAPI schema.
/// Schema path: #/components/schemas/VolumeInList
/// 
/// Volume list item model
/// </summary>
public partial class VolumeInList
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("size")]
  public double? Size { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalUsage")]
  public double? TotalUsage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totalInstancesCount")]
  public int? TotalInstancesCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attachedInstancesCount")]
  public int? AttachedInstancesCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("containersCount")]
  public int? ContainersCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("volumeInstances")]
  public List<VolumeInstance>? VolumeInstances { get; set; }
}
