//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.MagicContainers.Models;

/// <summary>
/// VolumeMountRequest from OpenAPI schema.
/// Schema path: #/components/schemas/VolumeMountRequest
/// </summary>
public partial class VolumeMountRequest
{
  [Required]
  [MinLength(1)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [Required]
  [MinLength(1)]
  [RegularExpression(@"^/(?!.*//)(?!.*\.\.)(?!.*\s)([a-zA-Z0-9._-]+/?)+$")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("mountPath")]
  public string? MountPath { get; set; }
}
