//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// CaptionValidationModel from OpenAPI schema.
/// Schema path: #/components/schemas/CaptionValidationModel
/// </summary>
public partial class CaptionValidationModel
{
  /// <summary>
  /// Denotes whether uploaded captions file was valid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("valid")]
  public bool? Valid { get; set; }

  /// <summary>
  /// When uploaded file was invalid, will contain errors found
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("errorList")]
  public List<string?>? ErrorList { get; set; }

  /// <summary>
  /// When uploaded file was valid but non-breaking issues were found, will contain issues found
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("warningList")]
  public List<string?>? WarningList { get; set; }

  /// <summary>
  /// UI-friendly summary of warnings found in the uploaded captions file
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("warningMessage")]
  public string? WarningMessage { get; set; }
}
