//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// CreateVideoModel from OpenAPI schema.
/// Schema path: #/components/schemas/CreateVideoModel
/// </summary>
public partial class CreateVideoModel
{
  /// <summary>
  /// The title of the video
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The ID of the collection where the video will be put
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("collectionId")]
  public string? CollectionId { get; set; }

  /// <summary>
  /// Video time in ms to extract the main video thumbnail.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailTime")]
  public int? ThumbnailTime { get; set; }
}
