//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// FetchVideoRequest from OpenAPI schema.
/// Schema path: #/components/schemas/FetchVideoRequest
/// </summary>
public partial class FetchVideoRequest
{
  /// <summary>
  /// The URL from which the video will be fetched from.
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }

  /// <summary>
  /// The headers that will be sent along with the fetch request.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("headers")]
  public Dictionary<string, string?>? Headers { get; set; }

  /// <summary>
  /// The title that will be set to video.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }
}
