//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// PaginationListOfCollectionModel from OpenAPI schema.
/// Schema path: #/components/schemas/PaginationListOfCollectionModel
/// </summary>
public partial class PaginationListOfCollectionModel
{
  /// <summary>
  /// The total number of items that can be returned
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("totalItems")]
  public long? TotalItems { get; set; }

  /// <summary>
  /// The current page of the response
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currentPage")]
  public long? CurrentPage { get; set; }

  /// <summary>
  /// The number of items returned per page
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("itemsPerPage")]
  public int? ItemsPerPage { get; set; }

  /// <summary>
  /// The result items on the current result
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("items")]
  public List<CollectionModel>? Items { get; set; }
}
