//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// SmartGenerateFeaturesStatusModel from OpenAPI schema.
/// Schema path: #/components/schemas/SmartGenerateFeaturesStatusModel
/// </summary>
public partial class SmartGenerateFeaturesStatusModel
{
  /// <summary>
  /// Smart generate status for the video title, when applicable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public SmartGenerateStatus? Title { get; set; }

  /// <summary>
  /// Smart generate status for the video description, when applicable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public SmartGenerateStatus? Description { get; set; }

  /// <summary>
  /// Smart generate status for chapters, when applicable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("chapters")]
  public SmartGenerateStatus? Chapters { get; set; }

  /// <summary>
  /// Smart generate status for moments, when applicable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("moments")]
  public SmartGenerateStatus? Moments { get; set; }
}
