//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// TranscribeSettings from OpenAPI schema.
/// Schema path: #/components/schemas/TranscribeSettings
/// </summary>
public partial class TranscribeSettings
{
  /// <summary>
  /// List of languages that will be used as target languages, use ISO 639-1 language codes.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("targetLanguages")]
  public List<string?>? TargetLanguages { get; set; }

  /// <summary>
  /// Whether video title should be automatically generated.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("generateTitle")]
  public bool? GenerateTitle { get; set; }

  /// <summary>
  /// Whether video description should be automatically generated.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("generateDescription")]
  public bool? GenerateDescription { get; set; }

  /// <summary>
  /// Whether video chapters should be automatically generated.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("generateChapters")]
  public bool? GenerateChapters { get; set; }

  /// <summary>
  /// Whether video moments should be automatically generated.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("generateMoments")]
  public bool? GenerateMoments { get; set; }

  /// <summary>
  /// Video source language, use ISO 639-1 language code.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sourceLanguage")]
  public string? SourceLanguage { get; set; }
}
