//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// UpdateVideoModel from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateVideoModel
/// </summary>
public partial class UpdateVideoModel
{
  /// <summary>
  /// The title of the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The ID of the collection where the video belongs
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("collectionId")]
  public string? CollectionId { get; set; }

  /// <summary>
  /// The list of chapters available for the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("chapters")]
  public List<ChapterModel>? Chapters { get; set; }

  /// <summary>
  /// The list of moments available for the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("moments")]
  public List<MomentModel>? Moments { get; set; }

  /// <summary>
  /// The meta tags added to the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("metaTags")]
  public List<MetaTagModel>? MetaTags { get; set; }
}
