//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// VideoStatisticsModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoStatisticsModel
/// </summary>
public partial class VideoStatisticsModel
{
  /// <summary>
  /// Shows the number of playback starts over time, with each data point representing the count of view starts in the corresponding UTC interval (hourly or daily). It is available at both the library level (aggregated across all videos) and the video level (for a single video). A playback start is counted once per viewer session per video and empty intervals are shown as zero.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("viewsChart")]
  public Dictionary<string, long>? ViewsChart { get; set; }

  /// <summary>
  /// Shows the cumulative time viewers spent watching over time, with each data point representing total watch time in the corresponding UTC interval (hourly or daily). It is available at both the library level (aggregated across all videos) and the video level (for a single video). Rewatches and repeated visits add to the total and empty intervals are shown as zero.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("watchTimeChart")]
  public Dictionary<string, long>? WatchTimeChart { get; set; }

  /// <summary>
  /// Shows the total number of playback starts by country for the selected time range. It is available at both the library level (aggregated across all videos) and the video level (for a single video). Each country’s value reflects unique playback starts per viewer session based on IP geolocation at playback start.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("countryViewCounts")]
  public Dictionary<string, long>? CountryViewCounts { get; set; }

  /// <summary>
  /// Shows the total watch time by country for the selected time range. It is available at both the library level (aggregated across all videos) and the video level (for a single video). Values reflect cumulative viewing time (rewatches and repeated visits add to the total) based on IP geolocation at playback start.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("countryWatchTime")]
  public Dictionary<string, long>? CountryWatchTime { get; set; }

  /// <summary>
  /// Indicates how engaging a specific video is on a 0–100 scale based on viewing duration and viewing patterns; higher values reflect stronger viewer retention. Reported at the video level only and may be unavailable when there isn’t enough viewing data.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("engagementScore")]
  public int? EngagementScore { get; set; }
}
