//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// VideoModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoModel
/// </summary>
public partial class VideoModel
{
  /// <summary>
  /// The ID of the video library that the video belongs to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("videoLibraryId")]
  public long VideoLibraryId { get; set; }

  /// <summary>
  /// The unique ID of the video
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("guid")]
  public string? Guid { get; set; }

  /// <summary>
  /// The title of the video
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The description of the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The date when the video was uploaded
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("dateUploaded")]
  public DateTimeOffset DateUploaded { get; set; }

  /// <summary>
  /// The number of views the video received
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("views")]
  public long Views { get; set; }

  /// <summary>
  /// Determines if the video is publically accessible
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("isPublic")]
  public bool IsPublic { get; set; }

  /// <summary>
  /// The duration of the video in seconds
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("length")]
  public int Length { get; set; }

  /// <summary>
  /// The status of the video. See VideoModelStatus.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public object? Status { get; set; }

  /// <summary>
  /// The framerate of the video
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("framerate")]
  public double Framerate { get; set; }

  /// <summary>
  /// The rotation of the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("rotation")]
  public int? Rotation { get; set; }

  /// <summary>
  /// The width of the original video file
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("width")]
  public int Width { get; set; }

  /// <summary>
  /// The height of the original video file
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("height")]
  public int Height { get; set; }

  /// <summary>
  /// The available resolutions of the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("availableResolutions")]
  public string? AvailableResolutions { get; set; }

  /// <summary>
  /// Encoded output codecs of the video
  /// </summary>
  [Required]
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("outputCodecs")]
  public string? OutputCodecs { get; set; }

  /// <summary>
  /// The number of thumbnails generated for this video
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailCount")]
  public int ThumbnailCount { get; set; }

  /// <summary>
  /// The current encode progress of the video
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("encodeProgress")]
  public int EncodeProgress { get; set; }

  /// <summary>
  /// The amount of storage used by this video
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("storageSize")]
  public long StorageSize { get; set; }

  /// <summary>
  /// The list of captions available for the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("captions")]
  public List<CaptionModel>? Captions { get; set; }

  /// <summary>
  /// Determines if the video has MP4 fallback files generated
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasMP4Fallback")]
  public bool HasMP4Fallback { get; set; }

  /// <summary>
  /// The ID of the collection where the video belongs
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("collectionId")]
  public string? CollectionId { get; set; }

  /// <summary>
  /// The file name of the thumbnail inside of the storage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailFileName")]
  public string? ThumbnailFileName { get; set; }

  /// <summary>
  /// The CDN URL of the thumbnail
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailUrl")]
  public string? ThumbnailUrl { get; set; }

  /// <summary>
  /// Thumbnail blurhash to show while the actual thumbnail is being loaded
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("thumbnailBlurhash")]
  public string? ThumbnailBlurhash { get; set; }

  /// <summary>
  /// The average watch time of the video in seconds
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("averageWatchTime")]
  public long AverageWatchTime { get; set; }

  /// <summary>
  /// The total video watch time in seconds
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("totalWatchTime")]
  public long TotalWatchTime { get; set; }

  /// <summary>
  /// The automatically detected category of the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("category")]
  public string? Category { get; set; }

  /// <summary>
  /// The list of chapters available for the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("chapters")]
  public List<ChapterModel>? Chapters { get; set; }

  /// <summary>
  /// The list of moments available for the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("moments")]
  public List<MomentModel>? Moments { get; set; }

  /// <summary>
  /// The list of meta tags that have been added to the video
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("metaTags")]
  public List<MetaTagModel>? MetaTags { get; set; }

  /// <summary>
  /// The list of transcoding messages that describe potential issues while the video was transcoding
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transcodingMessages")]
  public List<TranscodingMessageModel>? TranscodingMessages { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("jitEncodingEnabled")]
  public bool? JitEncodingEnabled { get; set; }

  /// <summary>
  /// Aggregate smart generate status derived from per-feature statuses when present: InProgress, then Queued, then Failed, then Finished; otherwise the stored legacy value. See SmartGenerateFeaturesStatus.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smartGenerateStatus")]
  public object? SmartGenerateStatus { get; set; }

  /// <summary>
  /// Per-feature smart generate statuses (title, description, chapters, moments). Null for a feature on legacy rows.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smartGenerateFeaturesStatus")]
  public object? SmartGenerateFeaturesStatus { get; set; }

  /// <summary>
  /// Determines if video has the original file available in storage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hasOriginal")]
  public bool? HasOriginal { get; set; }

  /// <summary>
  /// Original uploaded file SHA256 hash
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("originalHash")]
  public string? OriginalHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hasHighQualityPreview")]
  public bool? HasHighQualityPreview { get; set; }
}
