//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// VideoPlayDataModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoPlayDataModel
/// </summary>
public partial class VideoPlayDataModel
{
  /// <summary>
  /// Video data.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("video")]
  public VideoModel? Video { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("libraryName")]
  public string? LibraryName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("pullZoneId")]
  public long? PullZoneId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("captionsPath")]
  public string? CaptionsPath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("seekPath")]
  public string? SeekPath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("thumbnailUrl")]
  public string? ThumbnailUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fallbackUrl")]
  public string? FallbackUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("videoPlaylistUrl")]
  public string? VideoPlaylistUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("originalUrl")]
  public string? OriginalUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("previewUrl")]
  public string? PreviewUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("controls")]
  public string? Controls { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enableDRM")]
  public bool? EnableDrm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("drmVersion")]
  public int? DrmVersion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("playerKeyColor")]
  public string? PlayerKeyColor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vastTagUrl")]
  public string? VastTagUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("viAiPublisherId")]
  public string? ViAiPublisherId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("captionsFontSize")]
  public int? CaptionsFontSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("captionsFontColor")]
  public string? CaptionsFontColor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("captionsBackground")]
  public string? CaptionsBackground { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("uiLanguage")]
  public string? UiLanguage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowEarlyPlay")]
  public bool? AllowEarlyPlay { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tokenAuthEnabled")]
  public bool? TokenAuthEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enableMP4Fallback")]
  public bool? EnableMP4Fallback { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("showHeatmap")]
  public bool? ShowHeatmap { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fontFamily")]
  public string? FontFamily { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("playbackSpeeds")]
  public string? PlaybackSpeeds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("widevineMinClientSecurityLevel")]
  public int? WidevineMinClientSecurityLevel { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("widevineEmeRobustness")]
  public string? WidevineEmeRobustness { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("widevineSdOnlyForL3")]
  public bool? WidevineSdOnlyForL3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxSoftwareWidevineResolution")]
  public int? MaxSoftwareWidevineResolution { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("zoneTier")]
  public int? ZoneTier { get; set; }

  /// <summary>
  /// Determines if the video is currently playable using either playlist or original source.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isPlayable")]
  public bool? IsPlayable { get; set; }

  /// <summary>
  /// Determines if the HLS playlist is currently playable.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("isPlaylistPlayable")]
  public bool? IsPlaylistPlayable { get; set; }

  /// <summary>
  /// Preferred playback source for the current video state.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("preferredPlaybackSource")]
  public VideoPlaybackSource? PreferredPlaybackSource { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rememberPlayerPosition")]
  public bool? RememberPlayerPosition { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("customCss")]
  public string? CustomCss { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("exposeVideoMetadata")]
  public bool? ExposeVideoMetadata { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enableCompactControls")]
  public bool? EnableCompactControls { get; set; }
}
