//
// <auto-generated>
// Bunny Stream API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/stream.json
// API: Stream API
// Version: 1.5.29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Stream.Models;

/// <summary>
/// VideoHeatmapModel from OpenAPI schema.
/// Schema path: #/components/schemas/VideoHeatmapModel
/// </summary>
public partial class VideoHeatmapModel
{
  /// <summary>
  /// Timeline heatmap as segment-index to intensity (0–100). Keys represent consecutive segments from the start of the video; values are normalized so 100 equals the most‑watched segment. Missing segments imply 0.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("heatmap")]
  public Dictionary<string, int>? Heatmap { get; set; }
}
