//
// <auto-generated>
// Bunny Logging API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/logging.json
// API: bunny.net CDN Logging
// Version: v2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Logging.Models;

/// <summary>
/// LogQueryResponse from OpenAPI schema.
/// Schema path: #/components/schemas/LogQueryResponse
/// 
/// Paginated response wrapper for log queries.
/// </summary>
public partial class LogQueryResponse
{
  /// <summary>
  /// Log entries matching the query, in the requested sort order.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public List<LogEntry>? Data { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("pagination")]
  public PaginationInfo Pagination { get; set; } = null!;

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("query")]
  public QuerySummary Query { get; set; } = null!;
}
