//
// <auto-generated>
// Bunny Logging API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/logging.json
// API: bunny.net CDN Logging
// Version: v2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Bunny.Logging.Models;

/// <summary>
/// PaginationInfo from OpenAPI schema.
/// Schema path: #/components/schemas/PaginationInfo
/// </summary>
public partial class PaginationInfo
{
  /// <summary>
  /// Offset that was applied to this query.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("offset")]
  public long Offset { get; set; }

  /// <summary>
  /// Limit that was applied to this query.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("limit")]
  public int Limit { get; set; }

  /// <summary>
  /// Number of entries actually returned (≤ bunnynet_cdn_log_api.Models.V2.PaginationInfo.Limit).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("returned")]
  public int Returned { get; set; }

  /// <summary>
  /// True if more results are available beyond this page.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("hasMore")]
  public bool HasMore { get; set; }
}
