//
// <auto-generated>
// Bunny Logging API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/logging.json
// API: bunny.net CDN Logging
// Version: v2
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.Logging.Models;

#nullable enable

namespace Apigen.Bunny.Logging;

/// <summary>
/// Interface for Logging v1 operations
/// </summary>
public partial interface ILoggingV1Client
{
  /// <summary>
  /// Query logs (legacy)
  /// Operation: GET /{date}/{pullZoneId}.log
  /// </summary>
  Task<Stream> GetAsync(string date, long pullZoneId, GetLoggingV1Request? request = null, CancellationToken cancellationToken = default);

}
