//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.MagicContainers.Models;

#nullable enable

namespace Apigen.Bunny.MagicContainers;

/// <summary>
/// Interface for Applications operations
/// </summary>
public partial interface IApplicationsClient
{
  /// <summary>
  /// Deploy Application
  /// Operation: POST /apps/{appId}/deploy
  /// </summary>
  Task DeployAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Undeploy Application
  /// Operation: POST /apps/{appId}/undeploy
  /// </summary>
  Task UndeployAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Application Statistics
  /// Operation: GET /apps/{appId}/statistics
  /// </summary>
  Task<Statistics> GetApplicationStatisticsAsync(string appId, GetApplicationStatisticsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Application Usage Summary
  /// Operation: GET /apps/{appId}/summary
  /// </summary>
  Task<UsageSummary> GetApplicationUsageSummaryAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Application Overview
  /// Operation: GET /apps/{appId}/overview
  /// </summary>
  Task<Overview> GetApplicationOverviewAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add Application
  /// Operation: POST /apps
  /// </summary>
  Task<AddApplicationResponse> AddAsync(Apigen.Bunny.MagicContainers.Models.AddApplicationRequest addApplicationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Applications
  /// Operation: GET /apps
  /// </summary>
  Task<ListApplicationsResponse> ListAsync(ListApplicationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Patch Application
  /// Operation: PATCH /apps/{appId}
  /// </summary>
  Task<AddApplicationResponse> PatchAsync(string appId, Apigen.Bunny.MagicContainers.Models.PatchApplicationRequestPatchRequest patchApplicationRequestPatchRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Application
  /// Operation: PUT /apps/{appId}
  /// </summary>
  Task<AddApplicationResponse> UpdateAsync(string appId, Apigen.Bunny.MagicContainers.Models.AddApplicationRequest addApplicationRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get application
  /// Operation: GET /apps/{appId}
  /// </summary>
  Task<Application> GetAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Application
  /// Operation: DELETE /apps/{appId}
  /// </summary>
  Task DeleteAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Restart Application
  /// Operation: POST /apps/{appId}/restart
  /// </summary>
  Task RestartAsync(string appId, CancellationToken cancellationToken = default);

}
