//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.MagicContainers.Models;

#nullable enable

namespace Apigen.Bunny.MagicContainers;

/// <summary>
/// Interface for AutoscalingSettings operations
/// </summary>
public partial interface IAutoscalingSettingsClient
{
  /// <summary>
  /// Get Application Autoscaling
  /// Operation: GET /apps/{appId}/autoscaling
  /// </summary>
  Task<AutoscalingSettings> GetApplicationAutoscalingAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Application Autoscaling
  /// Operation: PUT /apps/{appId}/autoscaling
  /// </summary>
  Task UpdateApplicationAutoscalingAsync(string appId, Apigen.Bunny.MagicContainers.Models.AutoscalingSettings autoscalingSettings, CancellationToken cancellationToken = default);

}
