//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.MagicContainers.Models;

#nullable enable

namespace Apigen.Bunny.MagicContainers;

/// <summary>
/// Interface for ContainerRegistries operations
/// </summary>
public partial interface IContainerRegistriesClient
{
  /// <summary>
  /// List Container Registries
  /// Operation: GET /registries
  /// </summary>
  Task<ListContainerRegistriesResponse> ListAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Add container registry
  /// Operation: POST /registries
  /// </summary>
  Task<SaveContainerRegistryResult> AddContainerRegistryAsync(Apigen.Bunny.MagicContainers.Models.ContainerRegistryRequest containerRegistryRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Search Public Container Images
  /// Operation: POST /registries/public-images/search
  /// </summary>
  Task<List<ContainerImage>> SearchForPublicContainerImagesAsync(Apigen.Bunny.MagicContainers.Models.SearchPublicContainerImagesRequest searchPublicContainerImagesRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Container Images
  /// Operation: POST /registries/images
  /// </summary>
  Task<List<ContainerImage>> ListContainerImagesAsync(Apigen.Bunny.MagicContainers.Models.ListContainerImagesRequest listContainerImagesRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Container Registry
  /// Operation: PUT /registries/{registryId}
  /// </summary>
  Task<SaveContainerRegistryResult> UpdateContainerRegistryAsync(long registryId, Apigen.Bunny.MagicContainers.Models.ContainerRegistryRequest containerRegistryRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Container Registry
  /// Operation: GET /registries/{registryId}
  /// </summary>
  Task<ContainerRegistry> GetContainerRegistryAsync(long registryId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Container Registry
  /// Operation: DELETE /registries/{registryId}
  /// </summary>
  Task<RemoveContainerRegistryResult> DeleteContainerRegistryAsync(long registryId, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Container Image Tags
  /// Operation: POST /registries/tags
  /// </summary>
  Task<List<ContainerImageTag>> ListContainerImageTagsAsync(Apigen.Bunny.MagicContainers.Models.ListContainerImageTagsRequest listContainerImageTagsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Image Config
  /// Operation: POST /registries/image-config
  /// </summary>
  Task<ImageConfig> GetImageConfigAsync(Apigen.Bunny.MagicContainers.Models.ListContainerImageExposedPortsRequest listContainerImageExposedPortsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Container Image Digest
  /// Operation: POST /registries/digest
  /// </summary>
  Task<ImageTagInfo> GetContainerImageTagDigestAsync(Apigen.Bunny.MagicContainers.Models.GetContainerImageDigestByTagRequest getContainerImageDigestByTagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Container Config Suggestions
  /// Operation: POST /registries/config-suggestions
  /// </summary>
  Task<ContainerConfigSuggestions> GetContainerConfigSuggestionsAsync(Apigen.Bunny.MagicContainers.Models.GetContainerConfigSuggestionsRequest getContainerConfigSuggestionsRequest, CancellationToken cancellationToken = default);

}
