//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.MagicContainers.Models;

#nullable enable

namespace Apigen.Bunny.MagicContainers;

/// <summary>
/// Interface for Log Forwarding operations
/// </summary>
public partial interface ILogForwardingClient
{
  /// <summary>
  /// List log-forwarding configurations
  /// Operation: GET /log/forwarding
  /// </summary>
  Task<ListLogForwardingResponse> ListLogForwardingConfigurationsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Create log forwarding configuration
  /// Operation: POST /log/forwarding
  /// </summary>
  Task<LogForwardingConfiguration> CreateLogForwardingConfigurationAsync(Apigen.Bunny.MagicContainers.Models.CreateLogForwardingRequest createLogForwardingRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get log-forwarding configuration
  /// Operation: GET /log/forwarding/{appId}
  /// </summary>
  Task<LogForwardingConfiguration> GetLogForwardingConfigurationAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update log-forwarding configuration
  /// Operation: PUT /log/forwarding/{appId}
  /// </summary>
  Task<LogForwardingConfiguration> UpdateLogForwardingConfigurationAsync(string appId, Apigen.Bunny.MagicContainers.Models.CreateLogForwardingRequest createLogForwardingRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete log-forwarding configuration
  /// Operation: DELETE /log/forwarding/{appId}
  /// </summary>
  Task DeleteLogForwardingConfigurationAsync(string appId, CancellationToken cancellationToken = default);

}
