//
// <auto-generated>
// Bunny MagicContainers API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/magic-containers.json
// API: Public API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Bunny.MagicContainers.Models;

#nullable enable

namespace Apigen.Bunny.MagicContainers;

/// <summary>
/// Interface for Volumes operations
/// </summary>
public partial interface IVolumesClient
{
  /// <summary>
  /// Update Volume
  /// Operation: PATCH /apps/{appId}/volumes/{volumeId}
  /// </summary>
  Task<UpdateVolumeResponse> UpdateAsync(string appId, string volumeId, Apigen.Bunny.MagicContainers.Models.PatchVolumeRequestPatchRequest patchVolumeRequestPatchRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete All Volume Instances
  /// Operation: DELETE /apps/{appId}/volumes/{volumeId}
  /// </summary>
  Task<DeleteAllVolumeInstancesResponse> DeleteAsync(string appId, string volumeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Volumes
  /// Operation: GET /apps/{appId}/volumes
  /// </summary>
  Task<ListVolumesResponse> ListAsync(string appId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Detach Volume
  /// Operation: POST /apps/{appId}/volumes/{volumeId}/detach
  /// </summary>
  Task<DetachVolumeResponse> DetachAsync(string appId, string volumeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Volume Instance
  /// Operation: DELETE /apps/{appId}/volumes/{volumeId}/instances/{instanceId}
  /// </summary>
  Task<DeleteVolumeInstanceResponse> DeleteVolumeInstanceAsync(string appId, string volumeId, string instanceId, CancellationToken cancellationToken = default);

}
