//
// <auto-generated>
// Bunny Shield API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/shield.json
// API: Bunny Shield API
// Version: v1
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Bunny.Shield;

/// <summary>
/// Request parameters for Retrieve custom WAF rules configured for the specified Shield Zone
/// Operation: GET /shield/waf/custom-rules/{shieldZoneId}
/// </summary>
public partial class GetCustomWafRulesRequest : BaseRequest
{
  /// <summary>
  /// (Optional) The page number of results.
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// (Optional) (Default: 10) The amount of results returned on one page.
  /// </summary>
  [JsonPropertyName("perPage")]
  public int? PerPage { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Page != null)
      queryParams["page"] = Page;
    if (PerPage != null)
      queryParams["perPage"] = PerPage;

    return queryParams.ToQueryString();
  }
}
